### PR TITLE
test: increase AccessControlFacet test coverage to 100%

### PR DESCRIPTION
**Pull request by gitcoindev**
Add test cases to verify that hasRole and getRoleAdmin functions work correctly.

### CODE REVIEW

**Comment by gitcoindev** [comment]
This pull request is still a wip / draft. I will let know when it is ready for the review.

**Comment by gitcoindev** [comment]
Ready for the review, AccessControlFacet covered 100% https://coveralls.io/jobs/131940854/source_files/17384392607

**Comment by molecula451** [comment]
why this was an issue @gitcoindev

**Comment by gitcoindev** [comment]
@molecula451 the background is that @pavlovcik asked me after consulting @rndquu to investigate AI (GitHub copilot / cursor / Bito) to increase test coverage in dollar repository. From initial prompts I got a few hints but will continue semi-automatically and submit a few prs in the future. AI suggests mostly to cover missing reverts. So it was never an issue but a good way to learn the code base from inside, plus increasing test coverage improves a safety net for any future development.

**Comment by molecula451** [comment]
i see, i notice this was some tests that were missing in the corresponding test file from the facets, thus increasing the coverage

**Comment by gitcoindev** [comment]
> i see, i notice this was some tests that were missing in the corresponding test file from the facets, thus increasing the coverage

Yes, that was the case. Perhaps I will open an issue in GitHub and link to it so it would be visible. I am going to concentrate on this and try to fully cover all facets this week.

**Comment by molecula451** [comment]
please also add difference between old coveralls and new coverage to increase broader perspective

**Review by rndquu — APPROVED** [review]

**Review by molecula451 — APPROVED** [review]

**Pull request merged**
