### PR TITLE
feat: add commit hash URL

### LINKED ISSUE #290: Display Commit Hash and semver on UI
The `main` branch needs to be manually updated on occasion. This shouldn't be automated because we (especially me) should review all the code changes to look for rugs before hosting on our main website. 

To serve as a reminder, it will probably be wise to display a version number, which can be clicked to see the commit that's deployed. It will be easy to see how far the code is out of date for with this feature.

Just expose the commit hash for now, and eventually we should follow a semantic versioning system and show that with the hash or instead (decision for a later date.)

***
> I just realized that `production` is just out of date. @ubiquity/bounty-masters we should figure a process to make sure stuff like this doesn't happen again.

> https://531ffccd.ubiquity-dollar-development.pages.dev/ from https://github.com/ubiquity/ubiquity-dollar/runs/8485554679

> image

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/283#issuecomment-1278109550_

### PR DESCRIPTION
**Pull request by rndquu**
Resolves #290 

Adds URL with `dapp` package version number which leads to currently deployed commit hash

Displayed in the bottom right corner

### CODE REVIEW

**Comment by 0x4007** [comment]
@0xcodercrane another instance of "Approve and run" can you do some research to resolve this issue?

Screenshot 2022-12-07 at 04 31 52

**Comment by 0x4007** [comment]
The good news is that it still appears to run the CI/CD even if I approve the run much later.

**Comment by rndquu** [comment]
@pavlovcik 

1. So currently version from `package.json` is displayed with a link to commit hash. Should I change displaying version from `package.json` to commit hash?

from `<a href="https://github.com/ubiquity/ubiquity-dollar/commit/[COMMIT_HASH]">1.0.1</a>` to `<a href="https://github.com/ubiquity/ubiquity-dollar/commit/[COMMIT_HASH]">[COMMIT_HASH]</a>`

2. This PR implies that production build is deployed on vercel. But I can see that development preview build is deployed on netlify. Where will production build be finally deployed? On vercel or netlify?

**Comment by 0x4007** [comment]
1. Yes use a commit hash- at least until we create a new bounty to semver merges to `main` then we can display both on the UI! also the `<a>` you present appears to be correct.
2. Merges to `main` get deployed using Cloudflare Pages. `uad.ubq.fi` is pointing to our Cloudflare pages.

Netlify is used for the CI/CD on every commit on every branch. I believe we stopped using Vercel because they charge money. We also stopped using Fleek because their builds were unreliable.

**Comment by 0x4007** [comment]
I had to approve to run again... @0xcodercrane something definitely changed!

**Comment by rndquu** [comment]
the ci error is `Could not instantiate forked environment with fork url: https://rpc.ankr.com/eth`

I believe this is some weird foundry issue, could somebody run the build process again?

**Comment by 0x4007** [comment]
This is very sad that there are so many issues with CI this evening. We really need to solve both of these.

**Comment by 0x4007** [comment]
> Deployment: Tue Dec 06 2022 22:12:05 GMT+0000 (Coordinated Universal Time)

I don't see it in this deployment.

image

**Comment by rndquu** [comment]
need another ci approve/run

**Comment by cuddle-dev** [comment]
> the ci error is `Could not instantiate forked environment with fork url: https://rpc.ankr.com/eth`
> 
> I believe this is some weird foundry issue, could somebody run the build process again?

I can clarify with that. Its not even foundry issue. but that error has been definitely caught up by foundry because ankr rpc isn't working properly sometimes due to their wrapped BNB hack.  They announced their infra would not affect by that incident but actually no, its getting affected. I hope it will recover everything from the incident.

**Comment by 0x4007** [comment]
> [Deployment: Thu Dec 08 2022 02:05:27 GMT+0000 (Coordinated Universal Time)](https://6391466163192913db41648a--ubiquity-dollar.netlify.app)



Oh @rndquu I understand why you asked the environments question (netlify/cloudflare) why not just always display the commit hash? I can't see how it looks on the deployment!

To clarify, these are all technically preview deployments on netlify. But wouldn't it make sense to generalize the solution by using the `git` binary to render a commit hash? For example, use node to run a shell command 

```shell
$ git rev-parse HEAD
0a7c5ed38f8b7c5ed38f8b7c5ed38f8b7c5ed38f
```

**Comment by rndquu** [comment]
@pavlovcik 

getting commit hash from local `.git` folder now

need ci run

**Comment by 0x4007** [comment]
> need ci run

Since this seems to affect you more than the others, perhaps you may be motivated to investigate #362

**Pull request merged**
