### PR TITLE
issue_161 - Change Price Stablization InterfaceChange Price..

### LINKED ISSUE #161: Change Price Stablization Interface
So talked with Alex. Think we can get rid of the TWAP price and keep the 3CRV Price as the main point. Recommend changing "3-CRV Swap Price" to "Ubiquity Dollar Spot Price." For the TWAP Price, I think you can have a small question mark around "Ubiquity Dollar Spot Price" and when someone hovers over it, the menu can show the TWAP Price.

2022-05-12 20_43_39-Dashboard _ Ubiquity Dollar

Small Question Mark can look something like this. 
2022-05-12 21_21_21-Inverse Finance - INV

2022-05-12 21_22_28-Inverse Finance - INV

### PR DESCRIPTION
**Pull request by 0xautohub**
1. Added exclamation mark and question mark to ui/JsxIcon.tsx
2. Used predefined Tooltip in ui for SPOT Price tooltip
Closes #161

### CODE REVIEW

**Comment by sunny0714** [comment]
[https://github.com/ubiquity/ubiquity-dollar/issues/161](url)

**Comment by 0x4007** [comment]
@sunny0714 let us @zapaz try and fix our CI/CD using this PR as a test. Please give us the week to finish our review on this! Thank you!

**Comment by 0xautohub** [comment]
> @sunny0714 let us @zapaz try and fix our CI/CD using this PR as a test. Please give us the week to finish our review on this! Thank you!

Hey @pavlovcik Thanks for your reply. Okay!!!

**Comment by 0x4007** [comment]
Hey @sunny0714 sorry for the delay I'll also send the full UBQ bonus - what is your Ethereum mainnet USDC wallet address?

**Comment by cuddle-dev** [comment]
Github ci/cd fails on building UI. it needs to be fixed before getting merged 
https://github.com/ubiquity/ubiquity-dollar/runs/8076230153?check_suite_focus=true
can you take a look at it? @sunny0714

**Comment by 0xautohub** [comment]
> Hey @sunny0714 sorry for the delay I'll also send the full UBQ bonus - what is your Ethereum mainnet USDC wallet address?

Hey @pavlovcik I'm okay. Sorry for the late response, I didn't get any notification
This is my Binance address (ERC20 and BEP20 compatible)
0xfe1c4a93a97be87b3e45ef573c936a89eb5b61f1
Thanks

**Comment by 0xautohub** [comment]
> 

Hey @0xcodercrane let me have a quick look

**Comment by 0xautohub** [comment]
I found that there are many changes on repo when trying to commit to fix the build error.
so I have pulled the repo and run "yarn run:ui", but got this error. Seems current commit is not stable
image

**Comment by 0x4007** [comment]
> Hey @pavlovcik I'm okay. Sorry for the late response, I didn't get any notification This is my Binance address (ERC20 and BEP20 compatible) 0xfe1c4a93a97be87b3e45ef573c936a89eb5b61f1 Thanks

https://etherscan.io/tx/0xf51a3510913499197bf8e9ca6d8a88cdb403432a37b8382085f36aff9cd2fde2

You need a self hosted wallet to receive UBQ

**Comment by 0x4007** [comment]
I addressed this in the reskin. Technically went for a layout change vs hiding the TWAP/SPOT but since you already did the work and we were late to review, you should still get paid for it. No more work needed on this bounty. Thanks @sunny0714!

**Comment by 0xautohub** [comment]
> > Hey @pavlovcik I'm okay. Sorry for the late response, I didn't get any notification This is my Binance address (ERC20 and BEP20 compatible) 0xfe1c4a93a97be87b3e45ef573c936a89eb5b61f1 Thanks
> 
> https://etherscan.io/tx/0xf51a3510913499197bf8e9ca6d8a88cdb403432a37b8382085f36aff9cd2fde2
> 
> You need a self hosted wallet to receive UBQ

Hey @pavlovcik Received 👍

**Comment by 0xautohub** [comment]
> I addressed this in the reskin. Technically went for a layout change vs hiding the TWAP/SPOT but since you already did the work and we were late to review, you should still get paid for it. No more work needed on this bounty. Thanks @sunny0714!

Oh.. yes.. cool, thanks @pavlovcik

**Pull request closed without merging**
