### PR TITLE
Feat: Walletconnect V2

### LINKED ISSUE #614: update wallet as walletconnect is sunsetting in june
in the dapp we are using wallet connect 1.8 but 
[walletconnect v1 will be shutdown in june ](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595)

### PR DESCRIPTION
**Pull request by Steveantor**
**Setup .env:**

> NEXT_PUBLIC_WALLET_CONNECT_ID = https://cloud.walletconnect.com/sign-in > Create New Project
> NEXT_PUBLIC_JSON_RPC_URL = RPC URL

Resolves #614

### CODE REVIEW

**Comment by pavlovcik** [comment]
Looks suspicious image

**Review by 0x4007 — CHANGES_REQUESTED** [review]
Looks suspicious image

**Comment by Steveantor** [comment]
> Looks suspicious image

You forgot the set up the .env variables @pavlovcik

**Comment by 0x4007** [comment]
Can you DM me the values?

**Review by zgorizzo69 — APPROVED** [review]
works for me !

**Review by 0x4007 — APPROVED** [review]

**Comment by 0x4007** [comment]
I think force pushing is causing an issue. @Steveantor you're going to need to fix the merge conflict.

**Comment by Steveantor** [comment]
> I think force pushing is causing an issue. @Steveantor you're going to need to fix the merge conflict.

@zgorizzo69 are u facing any issues?

**Comment by 0x4007** [comment]
Screenshot 2023-04-16 at 21 38 51

I was just going to merge it but GitHub is facing issues.

**Comment by Steveantor** [comment]
> Screenshot 2023-04-16 at 21 38 51
> 
> I was just going to merge it but GitHub is facing issues.

I can try merging @pavlovcik 
image

**Pull request merged**
