### PR TITLE
Fix/295 migrate to v3 metapool

### LINKED ISSUE #295: Migrate to V3 Metapool
crv.to is down and I can no longer find a swap UI for a v2 metapool that is currently functional. It appears that curve.fi dynamically can generate v3 metapool swap UIs, so this is a sound reason to migrate to a v3 pool officially. 

Here's the v3 pool (with no liquidity) I deployed some time ago: https://curve.fi/factory/124

        Unfortunately there is a blocking UI issue with crv.to so I need to figure out another UI for swapping on the metapools.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/225#issuecomment-1283003169_

### PR DESCRIPTION
**Pull request by hashedMae**
Resolves #295

### CODE REVIEW

**Comment by hashedMae** [comment]
Solidity script for migrating v2 metapool funds in both BondingV2 and ubq.eth to v3 metapool

**Comment by 0x4007** [comment]
Its a bit overwhelming to see all the file changes again from this and seemingly your other pull request. In order to wrap this bounty up, perhaps you can walk me through what I need to do in order to complete the migration while I use the `ubq.eth` EOA? 

I assume that we can merge in your other PR I reviewed deeply and then we can go back to review this one to see less changes? Otherwise you should rebase from a newer commit because there's a lot of redundant/old changes in this PR I think.

**Comment by hashedMae** [comment]
> Its a bit overwhelming to see all the file changes again from this and seemingly your other pull request. In order to wrap this bounty up, perhaps you can walk me through what I need to do in order to complete the migration while I use the `ubq.eth` EOA?
> 
> I assume that we can merge in your other PR I reviewed deeply and then we can go back to review this one to see less changes? Otherwise you should rebase from a newer commit because there's a lot of redundant/old changes in this PR I think.

Yeah, I'll wait until the other PR is merged then do what I need to so only the relevant files are reflected in the changes.

**Comment by 0x4007** [comment]
@hashedMae why was this closed? You can rebase this PR instead of https://github.com/ubiquity/ubiquity-dollar/pull/531 

Rebasing is pretty straightforward with the Git Graph extension for vscode.

```
Name: Git Graph
Id: mhutchie.git-graph
Description: View a Git Graph of your repository, and perform Git actions from the graph.
Version: 1.30.0
Publisher: mhutchie
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph
```

**Comment by hashedMae** [comment]
> @hashedMae why was this closed? You can rebase this PR instead of #531
> 
> Rebasing is pretty straightforward with the Git Graph extension for vscode.
> 
> ```
> Name: Git Graph
> Id: mhutchie.git-graph
> Description: View a Git Graph of your repository, and perform Git actions from the graph.
> Version: 1.30.0
> Publisher: mhutchie
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph
> ```

Had never heard of Git Graph and when I tried to rebase the last PR, it didn't pretty much nothing to clean up the differences.

**Comment by 0x4007** [comment]
Normally when you rebase it doesn't show all the redundant commits in the pull request because you "changed the base" commit to one that is after all those commits.

**Pull request closed without merging**
