### PR TITLE
Enable Etherscan Support for Diamond

### LINKED ISSUE #322: Enable Etherscan Support for Diamond
Depends on #300 to be completed.

We should add etherscan support for the [Diamond contract](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/Diamond.sol) using https://github.com/zdenham/diamond-etherscan

Corresponding [docs](https://github.com/zdenham/diamond-etherscan#how-to-support-etherscan-in-your-diamond)

What should be done:
1. Add a shell script which generates the dummy contract (step 1 from the [docs](https://github.com/zdenham/diamond-etherscan#how-to-support-etherscan-in-your-diamond))
2. Add dummy contract deployment to the development [deploy scripts](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/scripts/deploy/dollar/solidityScripting)
3. Add [EtherscanFacet](https://github.com/zdenham/diamond-etherscan/blob/main/contracts/facets/DiamondEtherscanFacet.sol) to our Diamond contract
4. In the dummy [deployment script](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/scripts/deploy/dollar/solidityScripting) set the proxy implementation to point to the deployed dummy

This way we would have an "etherscan friendly" development deploy which we would later modify for production deployment

### PR DESCRIPTION
**Pull request by 0xautohub**
Resolves #322

https://goerli.etherscan.io/address/0x69AB9Aa8a8C38c276E389d6EfaDE710B16D91100#writeProxyContract

### CODE REVIEW

**Comment by 0xautohub** [comment]
@sergfeldman @pavlovcik This PR is ready for a review
But this has a weird conventional commit message error in git action checking, not sure how to fix this checking, Seems it can be ignored

**Comment by Steveantor** [comment]
> @sergfeldman @pavlovcik This PR is ready for a review But this has a weird conventional commit message error in git action checking, not sure how to fix this checking, Seems it can be ignored

Was the same with me, I'm not sure if the conventional commit requirement is worthwhile at this state.
(It can be added later though)

Instead of focusing on the code, have to deal with some semantics.
@sunny0714

**Comment by 0x4007** [comment]
> > @sergfeldman @pavlovcik This PR is ready for a review But this has a weird conventional commit message error in git action checking, not sure how to fix this checking, Seems it can be ignored
> 
> Was the same with me, I'm not sure if the conventional commit requirement is worthwhile at this state. (It can be added later though)
> 
> Instead of focusing on the code, have to deal with some semantics. @sunny0714

I also had issues with it. Perhaps it is too aggressive. I'm not sure how other projects deal with this issue but I feel that perhaps the GitHub Action that we are using wasn't built in the best way.

**Comment by Steveantor** [comment]
> > > @sergfeldman @pavlovcik This PR is ready for a review But this has a weird conventional commit message error in git action checking, not sure how to fix this checking, Seems it can be ignored
> > 
> > 
> > Was the same with me, I'm not sure if the conventional commit requirement is worthwhile at this state. (It can be added later though)
> > Instead of focusing on the code, have to deal with some semantics. @sunny0714
> 
> I also had issues with it. Perhaps it is too aggressive. I'm not sure how other projects deal with this issue but I feel that perhaps the GitHub Action that we are using wasn't built in the best way.

I don't think CC is an industry standard,
many popular libs aren't using them for instance:

[react: 5329] https://github.com/reactjs/reactjs.org/pull/5329/commits
[next: 44163] https://github.com/vercel/next.js/pull/44163/commits
[oz: 3861] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3861/commits

**Comment by 0xautohub** [comment]
The commit messages have been updated to meet the conventional commits rules, no errors now @pavlovcik @sergfeldman

**Comment by cuddle-dev** [comment]
> The commit messages have been updated to meet the conventional commits rules, no errors now @pavlovcik @sergfeldman

This PR needs to be checked after https://github.com/ubiquity/ubiquity-dollar/pull/398 completed by @zgorizzo69. so we're gonna hold it off until @zgorizzo69 make sure its working properly. thanks for your patience @sunny0714

**Comment by 0xautohub** [comment]
> > The commit messages have been updated to meet the conventional commits rules, no errors now @pavlovcik @sergfeldman
> 
> This PR needs to be checked after #398 completed by @zgorizzo69. so we're gonna hold it off until @zgorizzo69 make sure its working properly. thanks for your patience @sunny0714

Cool

**Comment by 0x4007** [comment]
> [react: 5329] https://github.com/reactjs/reactjs.org/pull/5329/commits
> [next: 44163] https://github.com/vercel/next.js/pull/44163/commits
> [oz: 3861] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3861/commits

- https://github.com/facebook/react/commits/main?after=5fcf1a4b4c2150a1b9fe0de0144a82a053c63966+34&branch=main&qualified_name=refs%2Fheads%2Fmain

- https://github.com/vercel/next.js/commits/canary

- https://github.com/OpenZeppelin/openzeppelin-contracts/commits/master

So you bring up a good point @Steveantor but it looks like they are using some other convention with the # references within the commit messages 🤔

---

I moved this conversation into #423 in order to minimize polluting the conversation with not relevant topics.

**Pull request closed without merging**
