### PR TITLE
chore: facetCut tests

### LINKED ISSUE #838: Increase facet contracts forge / unit tests coverage
The goal is to facilitate AI and see if we can increase unit test coverage to 100% for all facets.

### PR DESCRIPTION
**Pull request by gitcoindev**
test: implement MockFacet skeleton and initial facetCut tests

Resolves: #838

### CODE REVIEW

**Comment by gitcoindev** [comment]
@rndquu @molecula451 I covered initial edge cases for the diamond facet cut. I am still working to cover add / replace / remove diamond facet cut operations, therefore switched this pull request to a draft. I will let you know when it is ready for the review.

**Comment by gitcoindev** [comment]
@rndquu , @molecula451 pull request ready for review, this one bumps test coverage to 76.6%

Development branch coverage: 70.9
PR branch coverage: 76.6

**Comment by molecula451** [comment]
good work, it's nice the coverage increased but can you mock a library instead? and import the struct, storage selectors etc from there? also the interface? Basically the whole diamond pattern are library importing would be much better architected (_the test_) @gitcoindev

**Comment by gitcoindev** [comment]
> good work, it's nice the coverage increased but can you mock a library instead? and import the struct, storage selectors etc from there? also the interface? Basically the whole diamond pattern are library importing would be much better architected (_the test_) @gitcoindev

hi @molecula451 thank you. Did I understand correct that you mean to create `test/diamond/facets/DiamondCutFacet.t.sol` and move test implementation with all imports there ?

**Review by molecula451 — APPROVED** [review]
looks good as is

**Comment by molecula451** [comment]
@gitcoindev re-checking this notice the lack commenting, at least a header comment explaining the intention, for future reference when reading the code

**Review by rndquu — APPROVED** [review]
@gitcoindev Good job

**Pull request merged**
