### PR TITLE
Fix set role admin

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90

### CODE REVIEW

**Comment by molecula451** [comment]
closing reopening? 😆

**Comment by gitcoindev** [comment]
@molecula451 I am sorry for the spam. I was confused and realized too late that we disabled GraphQL and contract storage changes workflows in development branch, but fix-review branch still has it enabled. So it is enabled and still failing here..

**Comment by molecula451** [comment]
yeah you pointed the disabled to the development branch lol

**Comment by molecula451** [comment]
doesn't look clean, the PR is gathering my commits to this PR, better just re-do the disable

**Comment by gitcoindev** [comment]
> doesn't look clean, the PR is gathering my commits to this PR, better just re-do the disable

You are right. Let me clean up this now. I will delete the pr, merge development to fix-review. Then base my pull request on the updated fix-review.

**Pull request closed without merging**
