### PR TITLE
resolve the slither errors

### LINKED ISSUE #536: Fix slither CI errors - II
This workflow https://github.com/ubiquity/ubiquity-dollar/blob/6e891801df973a6613b43c899381cdd244ad3fdb/.github/workflows/slither-analysis.yml produces some errors

You can find the failed CI run here: https://github.com/ubiquity/ubiquity-dollar/actions/runs/4065041113/jobs/6999216155

What should be done:
- update contracts to fix slither errors and make CI action pass

### PR DESCRIPTION
**Pull request by ghost**
Resolves #536

this pull request is to resolve the slither errors which was coming from 
yarn workspace @ubiquity/contracts run test:slither

### CODE REVIEW

**Comment by ghost** [comment]
umm why the above two got failed

**Comment by rndquu** [comment]
@AnakinSkywalkeer could you:
1. Check why the [build ci workflow](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5275427761/jobs/9540896247?pr=679) fails
2. Reenable the [slither ci workflow](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/slither-analysis.yml) (i.e. add "pull_request" and "push" handlers) so that we could check how it works

**Comment by rndquu** [comment]
@AnakinSkywalkeer I've converted this PR to draft, when it is ready for review pls set the PR back to "ready for review"

**Comment by ghost** [comment]
> @AnakinSkywalkeer I've converted this PR to draft, when it is ready for review pls set the PR back to "ready for review"

sure

**Comment by ghost** [comment]
nice build & test passed idk what to about the conventional commits is there any docs i can read about it?

**Comment by rndquu** [comment]
> nice build & test passed idk what to about the conventional commits is there any docs i can read about it?

https://github.com/ubiquity/ubiquity-dollar#committing-code

you should force push and make commit messages to use conventional commit naming

**Comment by ghost** [comment]
> > nice build & test passed idk what to about the conventional commits is there any docs i can read about it?
> 
> https://github.com/ubiquity/ubiquity-dollar#committing-code
> 
> you should force push and make commit messages to use conventional commit naming

ohh

**Comment by ghost** [comment]
ughh such a mess @rndquu should i close this and open up a new one and commit with conventional commits msg?

**Pull request closed without merging**
