### PR TITLE
Fix Build Process

### PR DESCRIPTION
**Pull request by 0x4007**
Refer to issue #7 

Basically the purpose of this branch is to totally clean up the directory structure, as well as repair the build process.

### CODE REVIEW

**Comment by Zequez** [comment]
How is this going? What seems to be the issue? What's the production log on Vercel?

**Comment by Zequez** [comment]
I would really love to see what Vercel is complaining about. It all seems to be working locally, although I'm not sure what is exactly that Vercel is running.

 @pavlovcik  is there any way you can add me to the project so I can see the output? All I get right now it's a 404 page.

**Comment by 0x4007** [comment]
#### 📝 Changed routes:


| [**/**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/) | [**/monitor**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/monitor) |
|:-:|:-:|
|<a href="https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/HgKC2QIaNViqJ3EpTn1ZpXs_upmo7A37zCKQptXc009pjt9rgvSoZV0tcHZIazoSdDaPUcBCm3yFxm6eBZdXVg.png">(view full size)</a> |<a href="https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/monitor">Screenshot of /monitor</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/dP1cm6QGrcpaRrs_xtMEVVYlBVV6rdOGMe9he8D2NgNlsBAG4vthRoM4ZcCBlJH7yB2bUxS8rmlZ2OqR5NG-kQ.png">(view full size)</a> |



| [**/styles**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles) | [**/styles/proxima**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima) |
|:-:|:-:|
|<a href="https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles">Screenshot of /styles</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/J6YvQ5sckFKLWXwOmhUiTfmL6vFP0IOnSGgwvGFU_MqlLe-cXUIOjlRrqjNwXj-0Hi2f61UA9Jgv2wBH2V9y3w.png">(view full size)</a> |<a href="https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima">Screenshot of /styles/proxima</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/kgL7lhQt0bAUJWSptXcAbml_NwwKmZ9ar-AEr6OCjlcrCH709sCWb1mMqcFYh0YoB53px3VpADnzTa_JwpYWaQ.png">(view full size)</a> |



| [**…les/proxima/2B04A9_A_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_A_0) | [**…roxima/2B04A9_A_0.eot?**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_A_0.eot?) |
|:-:|:-:|
|<a href="https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_A_0">Screenshot of /styles/proxima/2B04A9_A_0</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/XXLTnrlkKQ9WUoV1x5xyG5g-hPL0SJiMUwukkne9gQc35OA25uUmtmCBxtm0n7AGA2Td2mIt2XTxhDBQrptgkQ.png">(view full size)</a> |<a href="https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_A_0.eot?">Screenshot of /styles/proxima/2B04A9_A_0.eot?</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/WbFBIajIpAXieoOT1VXTMrbXAVVdjH_awVaUAlFwpGZyuZpi-dRtdSMcaJh-f9AfIh5C07g1d2S5sK35uolFAw.png">(view full size)</a> |



And 19 other routes:
- [**/styles/proxima/2B04A9_A_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_A_0)
- [**/styles/proxima/2B04A9_A_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_A_0)
- [**/styles/proxima/2B04A9_B_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_B_0)
- [**/styles/proxima/2B04A9_B_0.eot?**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_B_0.eot?)
- [**/styles/proxima/2B04A9_B_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_B_0)
- [**/styles/proxima/2B04A9_B_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_B_0)
- [**/styles/proxima/2B04A9_C_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_C_0)
- [**/styles/proxima/2B04A9_C_0.eot?**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_C_0.eot?)
- [**/styles/proxima/2B04A9_C_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_C_0)
- [**/styles/proxima/2B04A9_C_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_C_0)
- [**/styles/proxima/2B04A9_D_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_D_0)
- [**/styles/proxima/2B04A9_D_0.eot?**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_D_0.eot?)
- [**/styles/proxima/2B04A9_D_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_D_0)
- [**/styles/proxima/2B04A9_D_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_D_0)
- [**/styles/proxima/2B04A9_E_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_E_0)
- [**/styles/proxima/2B04A9_E_0.eot?**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_E_0.eot?)
- [**/styles/proxima/2B04A9_E_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_E_0)
- [**/styles/proxima/2B04A9_E_0**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/proxima/2B04A9_E_0)
- [**/styles/tailwind**](https://uad-ui-1yqwwlz66-pavlovcik.vercel.app/styles/tailwind)



Commit 129ba1f21c2b7ecd266e2bf87cb2a254adcc868b (https://uad-ui-1yqwwlz66-pavlovcik.vercel.app).

**Comment by Zequez** [comment]
Finally it's alive! 🎉

**Pull request merged**
