### PR TITLE
Global indicator

### PR DESCRIPTION
**Pull request by chriswudev**

### CODE REVIEW

**Review by Zequez — COMMENTED** [review]
Looks good so far. There are still some of the components which also make transactions and weren't changed to use this global indicator. Do you intend to continue with those before merging?

**Comment by chriswudev** [comment]
Yup, for sure!

**Review by Zequez — APPROVED** [review]

**Review by Zequez — APPROVED** [review]

**Comment by Zequez** [comment]
Alright it all looks great! The only thing I would change is to make the indicator fixed positioned on the page, that way it's always visible even when the page is scrolled down; and we can set `pointer-events: none`, I already got the change locally so I'll commit it.

**Comment by Zequez** [comment]
@pavlovcik this looks ready for merging

**Review by 0x4007 — APPROVED** [review]

**Pull request merged**
