### PR TITLE
refactor: remove IJar related files

### PR DESCRIPTION
**Pull request by rndquu**
Original [comment](https://github.com/ubiquity/ubiquity-dollar/pull/809#discussion_r1349496079)

This PR removes all pickle finance's jar related files

### CODE REVIEW

**Review by molecula451 — APPROVED** [review]
good catch, the unused interface was on my plan, but i have someworking at the direct governance facet

**Comment by rndquu** [comment]
@molecula451 

We have @gitcoindev now to help with review/development so it is better to stick to the "at least 2 approvals for a PR" rule

**Review by gitcoindev — COMMENTED** [review]
LGTM!

**Comment by gitcoindev** [comment]
I agree, also when a PR is clean and looks safe I do not mind if @molecula451 would merge alone. I did a review now and approved from my side as well.

**Pull request merged**
