### PR TITLE
Seo 4626

### PR DESCRIPTION
**Pull request by seosigoto**
initial one; made simple interface
from that structure I will make the function work.
will add configure more.
pls check;

### CODE REVIEW

**Comment by zapaz** [comment]
Hi @seosigoto 

Good start for ERC4626 implementation

You have also to add some factory contract that will instantiate these ERC4626 contracts , and that will be configured via the IVaultConfiger

Also, I didn't understood the allow and prevent strategies of the IVaultConfiger, can you explain ?

Finally updateuCRrate(uint) will handle default but not second part of Alex's request : 
"uCR Premium, a math formula (default would be a linear calculation, 1 USDC -> 2 uCR)
...
This gives us flexibility to implement exponential or logarithmic functions which may more efficiently produce our desired economic outcomes!"

**Comment by sergfeldman** [comment]
@seosigoto Hey, if you want to get effective feedback on a particular commit, it will be good to add a more detailed description of what was done and achieved in this commit.

**Comment by seosigoto** [comment]
This is for the interface: yield aggregator and includes ERC4626 Router common functions
The function for 1USD-> 2uCR will be declared in the function, and now only the name is shown.
Further work will cover the rate calculating function in this interface; IRateCalculator; we can get uCR amount when we call getUCRAmount function after RateCalculator deploy. currently, the getUCRamount function has 1 input, this can be changed.
This is the base function list, and I can add more if I need.

**Comment by sergfeldman** [comment]
Seo believes that the goal of this PR is to create an interface.
The task is done - PR completed and ready for review.

**Comment by pavlovcik** [comment]
@sergfeldman I suggest you break the [spec](https://github.com/ubiquity/ubiquity-dollar-development/discussions/171) into sprints and tag @zapaz and other experienced guys in for review at the end of each sprint

**Comment by sergfeldman** [comment]
Full testing is mandatory for accepting a task.
Currently, the first configuration is missing, making it hard to start testing this PR.
Alain created some configuration on his side, but he still gets errors in the smart contract.
@seosigoto please provide your configuration usable for testing.

**Pull request closed without merging**
