### PR TITLE
feat: refactor credits page to diamond contract

### LINKED ISSUE #786: UI: apply diamond to credits page
Original [issue](https://github.com/ubiquity/ubiquity-dollar/issues/783)

What should be done:
- take this [file](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts) and refactor the [credits](https://uad.ubq.fi/credits) page to use contracts from the new diamond architecture

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves: #786

### CODE REVIEW

**Comment by gitcoindev** [comment]
This is still a draft, I need to refactor components and test.

**Comment by gitcoindev** [comment]
Closing here.

**Comment by molecula451** [comment]
Why did You closed this PR? @gitcoindev

**Comment by gitcoindev** [comment]
> Why did You closed this PR? @gitcoindev

@molecula451 because about one hour after I started, @bojan07 wanted to pick up this task as he worked on a related one and I let him continue.

**Pull request closed without merging**
