### PR TITLE
639decrement storage slot hashes by one

### LINKED ISSUE #639: Low Security issue, Decrement storage slot hashes by one
## Description 
The storage slots/hashes have known pre-images. For example [LibCreditRedemptionCalculator.sol#L29-L30](https://github.com/ubiquity/ubiquity-dollar/blob/0c240d095cae6be599e020a8a6ba4d0a5fcf51c6/packages/contracts/src/dollar/libraries/LibCreditRedemptionCalculator.sol#L29-L30), [LibBondingCurve.sol#L19-L20](https://github.com/ubiquity/ubiquity-dollar/blob/0c240d095cae6be599e020a8a6ba4d0a5fcf51c6/packages/contracts/src/dollar/libraries/LibBondingCurve.sol#L19-L20), there are many others instances with the same issue.

## Recommendation
Quote from [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967)
> Furthermore, a -1 offset is added so the preimage of the hash cannot be known, further reducing the chances of a possible attack.

Current implementation is;
`bytes32 constant SLOT = keccak256("path.to.slot");`

Change it to:
`bytes32 constant SLOT = bytes32(uint256(keccak256("path.to.slot")) -1);`

### PR DESCRIPTION
**Pull request by eugenioclrc**
Resolves #639

I also have change the visibility of `UBIQUITY_CHEF_STORAGE_POSITION` and `TWAP_ORACLE_STORAGE_POSITION` from `public` to `internal`

### CODE REVIEW

**Review by rndquu — CHANGES_REQUESTED** [review]
@eugenioclrc 

Thank you for this PR, looks fine overall

One more thing, could you merge the latest `development` branch and apply the same update for this [slot](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L23) ?

**Review by zgorizzo69 — APPROVED** [review]

**Comment by 0x4007** [comment]
Hey there, following up on this

**Comment by sergfeldman** [comment]
@eugenioclrc Hey, please let us know when to expect the changes requested to this PR.

**Comment by eugenioclrc** [comment]
> @eugenioclrc Hey, please let us know when to expect the changes requested to this PR.

Hey guys the pull request is ready, @zgorizzo69 review it, have you take a look to it?

**Comment by sergfeldman** [comment]
@eugenioclrc Thank you!
Then waiting for the Rndquu review

**Review by rndquu — CHANGES_REQUESTED** [review]
@eugenioclrc pls also apply the update to this [slot](https://github.com/eugenioclrc/ubiquity-dollar/blob/639-Decrement-storage-slot-hashes-by-one/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L23)

**Review by rndquu — APPROVED** [review]

**Comment by rndquu** [comment]
@pavlovcik ready to merge

**Pull request merged**
