### PR TITLE
Github CI/CD actions

### LINKED ISSUE #223: Untrusted PR CI/CD
Cloudflare and Fleek seem to only work sometimes. We need reliable CI/CD to run on every commit on untrusted PRs for our bounty hunters in order to expedite the review process. More details later but must high level requirements:
- [ ] Must host deployments
- [ ] Must build and report results

### PR DESCRIPTION
**Pull request by cuddle-dev**

### CODE REVIEW

**Comment by 0x4007** [comment]
You will need to test with an untrusted PR from another account, or I will have to remove you as a contributor

**Comment by cuddle-dev** [comment]
> You will need to test with an untrusted PR from another account, or I will have to remove you as a contributor

Yeah I will test with a new account after everything done.  its still in progress

**Review by 0x4007 — APPROVED** [review]

**Comment by cuddle-dev** [comment]
ERC20: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by 0x4007** [comment]
> ERC20: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

[usdc](https://etherscan.io/tx/0xf14bc7a050521bf54e0fa1c37a2a155bd8800a6b1d162e0f8ac7f84a5d1461bd)
[ubq](https://etherscan.io/tx/0x2144c842f0e976639b1e752a9b683628876ac425d3800cb25c3bbe03c6bfd9b2)

**Pull request merged**
