### PR TITLE
feat: update wallet connection block design to match landing page design

### LINKED ISSUE #385: "Push to Start" to Connect Wallet
We should take the same code from the [home/landing page](https://ubq.fi) and have it replace the "please connect your wallet" message.

image

Landing page "push to start"

image

Current "please connect your wallet"

---

- [ ] Include the sound effect
- [ ] Only play sound effect and the animation of expansion when user successfully connects their wallet.
- [ ] Unsuccessful connect should play a different sound which I can personally compose later. For now, try any placeholder using the same sound API.
- [ ] Hide existing "Connect Wallet" button to instead have the user press this button to connect. (`visibility: invisible` should be sufficient for this bounty)
- [ ] When the user is "logged in" aka connected their wallet, the original disconnect button should be visible. 
- [ ] If the user invokes the disconnect button, the view for this should return to the beginning state (as it does when the user first loads the dApp.

### PR DESCRIPTION
**Pull request by kgelpes**
Resolves #385

- [x] Include the sound effect
- [x]  Only play sound effect and the animation of expansion when user successfully connects their wallet.
- [x]  Unsuccessful connect should play a different sound which I can personally compose later. For now, try any placeholder using the same sound API.
- [x]  Hide existing "Connect Wallet" button to instead have the user press this button to connect. (visibility: invisible should be sufficient for this bounty)
- [x]  When the user is "logged in" aka connected their wallet, the original disconnect button should be visible.
- [x]  If the user invokes the disconnect button, the view for this should return to the beginning state (as it does when the user first loads the dApp.

- Replaced `WalletNotConnected` with `WalletConnectionWall`: 
  - Displays children only if wallet is connected
  - Triggers animations and sounds on state change
- Created useDidUpdate hook that works like useEffect but ignores initial mount (using it to prevent sounds from triggering on mount)
- Created `sounds.ts` utility file with code from landing page adapted to react and ts
- Added `react-transition-group` library to handle mounting/unmounting animations
- Added `wallet-connect` classnames to change its visibility
- Added `"connectkit", "wagmi"` to cspell ignore list

image

https://user-images.githubusercontent.com/31427153/212189896-8a3dd11c-f48f-4fa8-88ee-1d7f5912bcd1.mov

### CODE REVIEW

**Comment by Steveantor** [comment]
It looks like the video has no sound, 
wanted to see if the sound effects are working as intended.

**Comment by kgelpes** [comment]
> It looks like the video has no sound, wanted to see if the sound effects are working as intended.

@Steveantor  You're correct, recorded now with sound. First error sound, then success:

https://user-images.githubusercontent.com/31427153/212441973-01350821-879a-48f3-9578-2765edb87a71.mov

**Comment by 0x4007** [comment]
This is really dope. Great work.

Unfortunately our auto-deploy bot stopped working just as you submitted your pull request making it more difficult to test this. I'll try re-running our continuous integration/deployment to see if I can test this before merging.

**Comment by 0x4007** [comment]
I just tested it locally and it looks great!

**Pull request merged**
