### PR TITLE
chore: UbiquityPool UI Update

### LINKED ISSUE #833: `dApp`: create UI for `UbiquityPool`
Depends on https://github.com/ubiquity/ubiquity-dollar/pull/832

There is the new [UbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract (facet) where users can mint and redeem `Dollar` tokens for collateral tokens.

Minting example:
1. User calls [mintDollar()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L77) and sends 100 `LUSD` as collateral
2. User gets 100 `Dollar` tokens

Redeeming example:
1. User calls [redeemDollar()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L93) and sends 100 `Dollar` tokens
2. User waits for 2 blocks to be mined
3. User calls [collectRedemption()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L107) and gets 100 `LUSD` collateral back

We should create a new UI page for the [UbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract and make sure that it works with the local [anvil deploy script](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/package.json#L31).

Since the [UbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract is forked from the [FraxPoolV3](https://github.com/FraxFinance/frax-solidity/blob/967002fc7f2c5ee9e175cabc763a776a8ed03e01/src/hardhat/contracts/Frax/Pools/FraxPoolV3.sol) contract we can take the Frax UI as an example:
- mint page: https://old.app.frax.finance/mint
- redeem page: https://old.app.frax.finance/redeem

Notice: the [getDollarPriceUsd()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L286) method may revert (because TWAP is not part of the deployment script, will be fixed in https://github.com/ubiquity/ubiquity-dollar/issues/827) so you will have to mock it 

P.S. All protocol contracts used in the UI can be found [here](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts)

Mint:
Screenshot 2023-11-15 at 16 18 53

Redeem:
Screenshot 2023-11-15 at 16 19 00

### PR DESCRIPTION
**Pull request by rndquu**
Resolves https://github.com/ubiquity/ubiquity-dollar/issues/833

### CODE REVIEW

**Comment by molecula451** [comment]
i think the best it's to design a new table from ground up, instead of mocking one similar to frax, what you think? @rndquu

**Comment by 0x4007** [comment]
Honestly I am heavily leaning towards making separate NON REACT separate pages per view. I feel like this would greatly simplify the development, at the risk of slightly non matching elements/behaviors across pages (this technically could be remedied with a shared generic stylesheet though!) 

I haven't worked on this repository for a while so I haven't made any initiative towards this, but I remember that dealing with the UI in the past was incredibly unwieldily. 

Anyways if you guys are more comfortable to proceed in React for now, then sure; but if I do get a chance to dive into this, there's a high chance I'm going to want to go raw (like in https://github.com/ubiquity/work.ubq.fi/)

**Comment by rndquu** [comment]
> i think the best it's to design a new table from ground up, instead of mocking one similar to frax, what you think? @rndquu

It won't be a frax'es mock but a simple UI enough to mint/redeem Dollars

> Honestly I am heavily leaning towards making separate NON REACT separate pages per view.

I like that react is widely used but don't like to choose over 100 hooks for different use cases. It was way simpler in the early days with class components.

> Anyways if you guys are more comfortable to proceed in React for now, then sure; but if I do get a chance to dive into this, there's a high chance I'm going to want to go raw (like in https://github.com/ubiquity/work.ubq.fi/)

We'll finish the Ubiquity pool page with the current stack so that we could test minting and redeeming of Dollar tokens. Raw js/css will eventually bring us to a mess. If you guys have experience with some simple frontend framework then suggestions are welcome.

**Comment by molecula451** [comment]
the thing is our whole frontend is make of React i think the approach you mention is good draw a simple table that shows minting/redeeming and a calculation and move on to further visual aspects, later on

**Comment by 0x4007** [comment]
We might be able to whip up a quick version of the UI by doing a `wget -r` lol

**Comment by rndquu** [comment]
I will open a new PR reflecting changes introduced in the audit

**Pull request closed without merging**
