### PR TITLE
Segment dApp into separate views

### LINKED ISSUE #61: Segment dApp Into Separate Views
We should start isolating functionalities of our protocol into different views

image
[https://app.olympusdao.finance/#/dashboard](https://app.olympusdao.finance/#/dashboard)

### PR DESCRIPTION
**Pull request by Zequez**
Actually closes #61

There are many improvements:

  - Each sub-app gets their own section
    - Price stabilization (To be replaced by the new debt coupons UI, but not yet)
    - Liquidity mining
    - Yield Farming
    - Launch party (disabled on production until the smart contracts are finished)
    - Token SWAP (we can improve this section to allow us to actually swap the tokens, and not just links to Curve and SushiSwap)
    - You can also manually access `/monitor` and the `/debt-coupons` UI which is under construction

 - Additionally the sidebar has links to [the Ubiquity intro (the landing)](https://landing.ubq.fi/en/), the Docs, the DAO docs, the Medium blog, and social links (Telegram, Twitter, Discord and Github) 
  - Improvements on the UI in general
  - The Inventory UI got a face-wash
  - The header also got a face-wash, it's displayed on the page if the sidebar is hidden, but if the sidebar is permanent, it's displayed on the sidebar

Screenshot 2022-04-14 at 13-28-10 Dashboard Ubiquity Dollar

Screen Shot 2022-04-14 at 13 38 21
Screen Shot 2022-04-14 at 13 38 12
Screen Shot 2022-04-14 at 13 38 06

Screenshot 2022-04-14 at 13-37-41 Dashboard Ubiquity Dollar

Screen Shot 2022-04-14 at 13 37 49

Screen Shot 2022-04-14 at 13 41 14
Screen Shot 2022-04-14 at 13 41 10

Shout out to @chriswudev  for helping with this

### CODE REVIEW

**Comment by 0x4007** [comment]
Face washing (lol) looks dope. Overall it feels a ton more polished. Good work team!

I wish that I could reference new issues conveniently here perhaps @sergfeldman can assist but

0. The logo for the dollar is different than that of the DAO. For reference: I included the logo of the Ubiquity Dollar product in the README.
image

1. This left more to be desired, namely, we have beautiful token icons which were not included here in the inventory
image

2. Details details details! Addressing overflow on buttons on liquidity mining for example:
image

3. Failure to render Launch Party view - I know that @chriswudev also had issues here, can someone please clarify the solution for me before pushing to prod? 
image

Satisfied with the improvements thus far. I'd consider only 3. to be mandetory to address before pushing to prod.

**Review by 0x4007 — CHANGES_REQUESTED** [review]
https://github.com/ubiquity/uad-ui/pull/83#issuecomment-1103589313

List item 3. must be addressed before merge @Zequez @chriswudev

**Comment by Zequez** [comment]
@pavlovcik

0. I did intend to use the Ubiquity logo and not the dollar logo; I will change the wording and replace it with just "Ubiquity" instead of "Ubiquity Dollar"; maybe we could add a subtitle or a slogan there.
1. Weird; it works fine in Firefox; but now that I check it seems to not load fine in Chrome; I'll inquire further into it.
2. Ah, I didn't see that because I don't have any bonds and the faucet for that token had broken (I just need to find another wallet with bonds to fix the faucet)
3. The launch party section is disabled on production; that error you get is because you are on mainnet; I'm thinking I can add a check that if the addresses aren't available on the addresses file then we indicate that the contracts aren't deployed on the current selected network yet; that way we don't get random errors for trying to use non-existent contracts.

**Comment by Zequez** [comment]
I just merged the launch-party-tweaks; since some of the feedback was regarding the launch party section I decided I would just pull those changes into this branch too.

The launch party itself it's programed to be disabled on production, so it shouldn't be a problem to deploy.

**Comment by 0x4007** [comment]
Sorry for the delay I just realized this is merging into `develop` instead of `main`! Lets setup that staging environment with @ubiquity-vercel

**Pull request merged**
