### PR TITLE
Update package.json

### LINKED ISSUE #516: `prettier` in `package.json` calling `forge fmt`
I just realized that this could be causing the discrepancy with the formatting. Because this task is named "prettier" it is possible that lint-staged is calling this instead of what we expect.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/417#discussion_r1085080563_

---
```
 "devDependencies": {
    "cspell": "latest",
    "prettier": "latest",
    "prettier-plugin-solidity": "latest"
  }
```

if we agree to keep prettier over forge fmt we need to :
1 - add the dev dependencies as stated above 
2 - update the overrides section of the  .prettierrc in the root folder

_Originally posted by @zgorizzo69 in  https://github.com/ubiquity/ubiquity-dollar/pull/417#issuecomment-1400977221_

### PR DESCRIPTION
**Pull request by ghost**
changes the versin of dev dependencies to latest

Resolves #516

### CODE REVIEW

**Review by 0x4007 — CHANGES_REQUESTED** [review]
This doesn't achieve the specification or pass conventional commits CI.

**Comment by ghost** [comment]
> 

ohh sorry what i forgot to do?

**Comment by ghost** [comment]
@pavlovcik oh so sorry i forgot to " update the overrides section of the .prettierrc in the root folder" seems like my bad

**Comment by ghost** [comment]
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false,
  "printWidth": 160,
  "htmlWhitespaceSensitivity": "strict",
  "plugins": ["prettier-plugin-solidity"],
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 80,
        "tabWidth": 4,
        "useTabs": false,
        "singleQuote": false,
        "bracketSpacing": false
      }
    }
  ]
}
what am i supposed to change 🤔

**Pull request closed without merging**
