### PR TITLE
refactor: remove Dollar mock

### PR DESCRIPTION
**Pull request by rndquu**
This PR: 
- removes mocks for Dollar, Credit, Ubiquistick, BondingShareV2 contracts
- refactors tests to use real contracts instead of mocks

### CODE REVIEW

**Comment by rndquu** [comment]
I canceled the "Compare Test Coverage" CI [workflow](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5834104241/job/15822931336?pr=758) because it run for too long (fixed [here](https://github.com/ubiquity/ubiquity-dollar/pull/760))

**Review by molecula451 — APPROVED** [review]

**Comment by molecula451** [comment]
> I canceled the "Compare Test Coverage" CI [workflow](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5834104241/job/15822931336?pr=758) because it run for too long (fixed [here](https://github.com/ubiquity/ubiquity-dollar/pull/760))

indeed.

**Comment by rndquu** [comment]
> > I canceled the "Compare Test Coverage" CI [workflow](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5834104241/job/15822931336?pr=758) because it run for too long (fixed [here](https://github.com/ubiquity/ubiquity-dollar/pull/760))
> 
> indeed.

The latest `development` branch has the fix, so I merged it and everything should pass now

**Comment by molecula451** [comment]
> > > I canceled the "Compare Test Coverage" CI [workflow](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5834104241/job/15822931336?pr=758) because it run for too long (fixed [here](https://github.com/ubiquity/ubiquity-dollar/pull/760))
> > 
> > 
> > indeed.
> 
> The latest `development` branch has the fix, so I merged it and everything should pass now

Yeah, updated everything

**Comment by 0x4007** [comment]
I don't have enough context to leave useful feedback.

**Pull request merged**
