### PR TITLE
Feat/curve migration

### PR DESCRIPTION
**Pull request by rndquu**
This PR refactors mainnet migrations to eliminate manual steps like:
- minting Dollar tokens for initial liquidity for the Curve's Dollar-3CRV metapool
- deploying Curve's metapool via https://curve.fi/#/ethereum/create-pool

P.S. I've tested the migration against the anvil forked from mainnet with [this](https://gist.github.com/rndquu/6797b0d7b9110e0b8faae6304ca600d9) test file which passed successfully

### CODE REVIEW

**Comment by gitcoindev** [comment]
Hi @rndquu i did an initial review, thank you for the comments explaining some values (e.g. ln(2) to calc time). I have not tested it yet. Do you plan to rework and merge together with UI changes?

**Comment by rndquu** [comment]
> Hi @rndquu i did an initial review, thank you for the comments explaining some values (e.g. ln(2) to calc time). I have not tested it yet. Do you plan to rework and merge together with UI changes?

The plan is to prepare the mainnet deployment script so that @pavlovcik could run `yarn deploy:mainnet` from `ubq.eth` EOA and be done with the deployment.

Right now the redeployment plan is this one:
1. Manually remove ~27k 3CRV tokens from the old Curve metapool (https://etherscan.io/address/0x20955CB69Ae1515962177D164dfC9522feef567E)
2. Setup [env variables](https://github.com/ubiquity/ubiquity-dollar/blob/b06fadac241ad1a5d298ef1dcd2054dd37911cbc/packages/contracts/.env.example) (in particular private key for `ubq.eth` EOA) and run `yarn deploy:mainnet` from https://github.com/ubiquity/ubiquity-dollar which:
a) deploys Dollar and Diamond contracts
b) mints initial Dollar tokens for `ubq.eth` EOA
c) deploys Curve's metapool
3. Manually add liquidity (Dollar + 3CRV) to the deployed metapool

Overall the deployment script is ready, I will run a few tests tomorrow of the deployed contracts on the forked state.

> Do you plan to rework and merge together with UI changes?

UI requires metapool to be deployed for it to work on the mainnet. So the plan is to prepare the mainnet deployment, check how it works, apply it and then update UI.

**Review by molecula451 — APPROVED** [review]
time to launch team 🚀

**Review by gitcoindev — APPROVED** [review]
I did an another review round and approving as well from my side.

**Pull request merged**
