### PR TITLE
Refactor Cloudflare Pages Build

### LINKED ISSUE #529: Cloudflare Pages Takes 20 Minutes to `Build foundry from the github source code`
Not sure why that is but I just watched the logs and its painfully slow. We should just wget/curl a compiled binary for Cloudflare CI. 

You should consider the timestamps in the logs and optimize whatever is taking a long time with sensible solutions for this bounty.

Logs from 8b8a91d292183b4ff5d8566c02c5fc8f727fe798 for reference. [ubiquity-dollar.6a4973f9-ef0b-49ae-aaac-90a39d0479f5.log](https://github.com/ubiquity/ubiquity-dollar/files/10539895/ubiquity-dollar.6a4973f9-ef0b-49ae-aaac-90a39d0479f5.log)

### PR DESCRIPTION
**Pull request by Steveantor**
**Project Setup (GitHub secrets):**

**CLOUDFLARE_ACCOUNT_ID =**
> https://dash.cloudflare.com/***/pages
> https://dash.cloudflare.com/abcd1234/pages
> (Here `abcd1234` is your account ID)

**CLOUDFLARE_API_TOKEN =**

> https://dash.cloudflare.com/profile/api-tokens > Create Token > API token templates > Edit Cloudflare Workers > Use Template
> 
> > Account Resources = All Resources
> 
> > Zone Resources = All Zones
> 
> (Detailed Instructions: https://developers.cloudflare.com/workers/wrangler/ci-cd/)

**CLOUDFLARE_ASSET_DIRECTORY =** 

> packages/dapp/dist

**CLOUDFLARE_PROJECT_NAME =**

> npm install -g wrangler
> wrangler login
> wrangler pages project create

_Cloudflare Pages_ couldn't build precompiled foundry package since it relies on
`GLIBC_2.25` and above which _Cloudflare Pages v1_ couldn't provide,
hence we're using _wrangler_ action.

Resolves #529

### CODE REVIEW

**Comment by 0x4007** [comment]
It doesn't look like its working? What is the Cloudflare URL? 

https://github.com/Steveantor/ubiquity-dollar/actions/runs/4157284638

**Comment by Steveantor** [comment]
> It doesn't look like its working? What is the Cloudflare URL?
> 
> https://github.com/Steveantor/ubiquity-dollar/actions/runs/4157284638

It's working, the Cloudflare action masks the full URL

https://cbde7a3a.ubiquity-dollar-wrangler.pages.dev/

@pavlovcik

**Comment by 0x4007** [comment]
How long does it take to build now?

**Comment by Steveantor** [comment]
> How long does it take to build now?

the foundry setup takes around 2s
the entire process is 4.23m
@pavlovcik

**Comment by 0x4007** [comment]
I'm trying to finish setup on this and I want to clarify that I have the continuous deployment linked automatically because I went to Cloudflare pages and linked in to this GitHub repo so Cloudflare handled everything automatically. Are you saying that I must uninstall that app or can I make your config work with that?

It seems like the reason why you want to manually set this up is only for wrangler. Perhaps there is a way to enable it via Cloudflare's first party solution?

image

For example, we programmed it to run the "Cloudflare CI" script so we could install wrangler there? I'll experiment.

---

I realized that 

```
      - name: Setup Foundry
        uses: onbjerg/foundry-toolchain@v1
```
Is hard to reproduce in a shell script so I'll just do it the way you suggested. It just seems less "automatic" in case we want to recreate this repo.

---

So should I delete `yarn build:ci:cloudflare` and its associated shell script?

**Comment by 0x4007** [comment]
I'm going to hardcode `packages/dapp/dist` instead of using the environment variable `CLOUDFLARE_ASSET_DIRECTORY` for future developers to change this more easily.

`CLOUDFLARE_PROJECT_NAME` doesn't really make sense to me on how to also hardcode in the `.yml` file.

I'm going to try the following:

```
$(yes | npx wrangler login && yes | npx wrangler pages project create)
```



---

When I try testing this locally, `yes | npx wrangler login` it opens my browser and asks me to click a button before proceeding. I presume that they have a different flow in the GitHub Actions environment?

**Pull request merged**
