### PR TITLE
Add WalletConnect

### PR DESCRIPTION
**Pull request by 3commascapital**

### CODE REVIEW

**Comment by 3commascapital** [comment]
it may very well be possible that the wallet is not available on non https domains. i am thinking that is half of the problem i am running into when trying to test locally. can't confirm it though. seeing odd things like
```
{"error":{"code":-32503,"message":"wallet address undefined"},"id":0,"jsonrpc":"2.0"}
```

**Comment by 3commascapital** [comment]
fixes #247

**Comment by 3commascapital** [comment]
close #247

**Comment by 3commascapital** [comment]
closes #247

**Comment by 3commascapital** [comment]
Unfortunately the documentation does not match exported code. this is going to take longer than anticipated

**Comment by 0x4007** [comment]
> Unfortunately the documentation does not match exported code. this is going to take longer than anticipated

Is this referring to WalletConnect's documentation? Or where can we improve our documentation?

**Comment by 3commascapital** [comment]
wallet connect documentation. https://docs.walletconnect.com/2.0/web3modal/react/installation

**Comment by 0x4007** [comment]
> wallet connect documentation. https://docs.walletconnect.com/2.0/web3modal/react/installation

Yeah for whatever its worth when I first researched this issue I learned that the commit labeled `v2.0.0` on the WalletConnect repo wasn't stable. I recall sifting through some other more recent commits and manually debugging those before getting the project up and running on my local.

I'm surprised that this is the state of their product and docs given the ubiquitousness of WalletConnect across the dApp ecosystem.

**Comment by 3commascapital** [comment]
a good move is probably to just find someone who has already implemented and use / emulate their code. this will be the next step

**Comment by 0x4007** [comment]
Hey @3commascapital I'm following up on this. Any luck?

**Pull request closed without merging**
