### PR TITLE
#643 - Solidity imported libraries should have a tagged version

### LINKED ISSUE #643: Solidity imported libraries should have a version
Currently its not clear what version of used libraries the protocolo is using;
https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules

What should be done:
1. Remove tags (because they are [not working](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule) in git submodules) and add branch names to [git submodules](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules) (perhaps this requires some code refactoring, make sure that [libs](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/lib) are also updated after settings branch names)
2. Remove duplicate entries in [git submodules](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules)

### PR DESCRIPTION
**Pull request by PhantomCracker**
Resolves #643

### CODE REVIEW

**Comment by PhantomCracker** [comment]
Run the following command to initialize and update the submodule with the specified branch:

git submodule update --init --remote

This command initializes the submodule and updates it to the latest commit on the specified branch.

**Review by 0x4007 — CHANGES_REQUESTED** [review]
I don't see tagged versions

**Comment by PhantomCracker** [comment]
> I don't see tagged versions

Updated

**Comment by 0x4007** [comment]
CI doesn't pass so we can't merge. You must be following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for your commit messages.

**Comment by PhantomCracker** [comment]
> CI doesn't pass so we can't merge. You must be following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for your commit messages.

Commits updated

**Review by 0x4007 — APPROVED** [review]

**Pull request merged**
