### PR TITLE
fix: build error on fresh yarn.lock file

### LINKED ISSUE #377: Build fails on a fresh yarn.lock
On a fresh install there is a build error `Module not found: Can't resolve 'jotai-immer'`

How to reproduce:
1. Delete `yarn.lock`
2. Run `yarn install`
3. Run `yarn build:all`

Gives the following:
```
➤ YN0000: No files changed, compilation skipped
➤ YN0000: info  - Linting and checking validity of types...
➤ YN0000: warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
➤ YN0000: 
➤ YN0000: ./pages/404.tsx
➤ YN0000: 12:82  Warning: Replace `Docs` with `⏎··············Docs⏎············`  prettier/prettier
➤ YN0000: 15:56  Warning: Replace `FAQ` with `⏎··············FAQ⏎············`  prettier/prettier
➤ YN0000: 18:77  Warning: Replace `Github` with `⏎··············Github⏎············`  prettier/prettier
➤ YN0000: 21:63  Warning: Replace `Discord` with `⏎··············Discord⏎············`  prettier/prettier
➤ YN0000: 24:58  Warning: Replace `Telegram` with `⏎··············Telegram⏎············`  prettier/prettier
➤ YN0000: 27:65  Warning: Replace `Twitter` with `⏎··············Twitter⏎············`  prettier/prettier
➤ YN0000: 
➤ YN0000: ./pages/index.tsx
➤ YN0000: 13:10  Warning: 'twapPrice' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/bonds/App.tsx
➤ YN0000: 36:10  Warning: 'showAdminComponents' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/lib/hooks/useDeployedAddress.tsx
➤ YN0000: 6:41  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
➤ YN0000: 
➤ YN0000: ./components/lib/hooks/useWeb3.tsx
➤ YN0000: 9:7  Warning: 'LOCAL_NODE_ADDRESS' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/redeem/UcrRedeem.tsx
➤ YN0000: 15:10  Warning: 'USDC_ADDRESS' is defined but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/staking/BondingSharesExplorer.tsx
➤ YN0000: 244:38  Warning: 'sharesBalance' is defined but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/utils/deployments.ts
➤ YN0000: 3:49  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
➤ YN0000: 7:96  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
➤ YN0000: 
➤ YN0000: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
➤ YN0000: info  - Creating an optimized production build...
➤ YN0000: Failed to compile.
➤ YN0000: 
➤ YN0000: ../../node_modules/jotai/esm/immer.mjs
➤ YN0000: Module not found: Can't resolve 'jotai-immer' in '/Users/rndquu/Public/projects/blockchain/ubiquity-dollar-rndquu/node_modules/jotai/esm'
➤ YN0000: 
➤ YN0000: Import trace for requested module:
➤ YN0000: ../../node_modules/jotai/esm/immer.mjs
➤ YN0000: ../../node_modules/@uniswap/widgets/dist/index.js
➤ YN0000: ./components/redeem/UcrRedeem.tsx
➤ YN0000: 
➤ YN0000: 
➤ YN0000: > Build failed because of webpack errors
➤ YN0000: Done in 1m 5s
```

### PR DESCRIPTION
**Pull request by Steveantor**
fix: this PR resolves the build error on fresh yarn.lock file

some sub/deps might not be strictly following semver)
We may also .gitignore yarn.lock (optional)

Resolves #377

### CODE REVIEW

**Comment by Steveantor** [comment]
@pavlovcik could look into this,
I've used the same conventional commit config on my repo and it passes there

✔https://github.com/Steveantor/conventional-checker/commit/4d4075e06373ec69d2848d73930e4c88476ae48d
❌https://github.com/Steveantor/conventional-checker/commit/44a0c4f4dc5fbba49393235d2c2576af72c36957

**Comment by 0x4007** [comment]
fix: build ✅

fix build ❌

**Comment by Steveantor** [comment]
> fix: build ✅
> 
> fix build ❌

could u rephrase please,
the title and description are identical between `#4d4075e` and this.
@pavlovcik

**Comment by 0x4007** [comment]
> > fix: build ✅
> > fix build ❌
> 
> could u rephrase please, the title and description are identical between `#4d4075e` and this. @pavlovcik

They are not identical. One has a colon separating the action from the description, the other lacks the colon.

https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by Steveantor** [comment]
Thanks for the assistance, the CC passed.
the other actions error might be related to updating the `package.json`

@pavlovcik

**Comment by 0x4007** [comment]
Looks like `yarn install` broke. @0xcodercrane any ideas here?

**Comment by cuddle-dev** [comment]
> Looks like `yarn install` broke. @0xcodercrane any ideas here?

you might need to update yarn.lock because you updated package.json. @Steveantor

**Comment by Steveantor** [comment]
> > Looks like `yarn install` broke. @0xcodercrane any ideas here?
> 
> you might need to update yarn.lock because you updated package.json. @Steveantor

could u test it locally and see if it's also working for you?

- remove node_modules

- remove yarn.lock

- run `yarn`

- run `yarn build:all`

IMO we shouldn't commit the _yarn.lock_ (`.gitignore`) to avoid #377 happening on future commits.
@0xcodercrane

**Comment by cuddle-dev** [comment]
We should DEFINITELY commit yarn.lock. @Steveantor 
But it needs to be generated on Ubuntu / Mac OS.

**Comment by Steveantor** [comment]
> We should DEFINITELY commit yarn.lock. @Steveantor But it needs to be generated on Ubuntu / Mac OS.

there should be a mechanism that builds from fresh _yarn.lock_, 
keeping _package.json_ `<>` _yarn.lock_ in sync.

what do you think?
@0xcodercrane @pavlovcik

**Comment by 0x4007** [comment]
> > We should DEFINITELY commit yarn.lock. @Steveantor But it needs to be generated on Ubuntu / Mac OS.
> 
> 
> 
> there should be a mechanism that builds from fresh _yarn.lock_, 
> 
> keeping _package.json_ `<>` _yarn.lock_ in sync.
> 
> 
> 
> what do you think?
> 
> @0xcodercrane @pavlovcik 

I don't understand your proposal but it's common practice to commit the lock file for dependency data integrity.

**Comment by Steveantor** [comment]
committed @pavlovcik

**Pull request merged**
