### PR TITLE
Revert "update github-script to v6.3.3 resolves #312"

### LINKED ISSUE #312: Update to use Environment Files in CI
[receive-pr-and-deploy](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3366042114/jobs/5582129072#step:3:664)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by cuddle-dev**
Reverts ubiquity/ubiquity-dollar#336

https://github.com/ubiquity/ubiquity-dollar/actions/runs/3515292767 --- It doesn't work if I merge your pr. @kfukue

### CODE REVIEW

**Comment by kfukue** [comment]
@0xcodercrane Let me take a look at the logs. Thanks for letting me know.

**Comment by kfukue** [comment]
@0xcodercrane This should fix that error but let's keep this PR open just in case we need to revert.
https://github.com/ubiquity/ubiquity-dollar/pull/338

**Comment by cuddle-dev** [comment]
Nodejs12. deprecated warning still exists.

**Comment by cuddle-dev** [comment]
I've updated actions/checkout and actions/setup-node versions to the latest ones here (https://github.com/ubiquity/ubiquity-dollar/pull/339) and it fixed deprecated warnings finally but its sort of 2 versions update. Most are done by @kfukue .
I appreciate it for @kfukue 's deep dive and good catch.  

@pavlovcik  @sergfeldman . Its time to pay @kfukue

**Comment by 0x4007** [comment]
@0xcodercrane can you merge and close this if it is complete? Payments are handled on the original issue/bounty conversation. Not on the PRs, in case bounty hunters delete their forks, we don't want to lose the history of payments for accounting reasons.

**Pull request merged**
