### PR TITLE
Added build badges

### LINKED ISSUE #482: Add build badges and update test coverage config
What should be done:
1. Add CI build badge at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md with the current CI build status (success or fail)
2. Add test coverage badge with % of lines covered by tests at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md
3. Remove the following files from the test coverage report:

- `src/dollar/libs/*`
- `src/dollar/mocks/*`
- `src/dollar/utils/*`
- `src/manager/libraries/*`
- `src/ubiquistick/MockUBQmanager.sol`
- `test/*`

Build badge docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

### PR DESCRIPTION
**Pull request by FibrinLab**
Resolves #482

### CODE REVIEW

**Comment by FibrinLab** [comment]
Screenshot 2023-02-06 at 19 20 16

@pavlovcik Seem to be peculiar to me alone. Could it be a repo setting.

**Comment by 0x4007** [comment]
Make sure you're using the latest version of `development` which passes CI. Then make sure to follow the CI steps locally so you know how to setup the workspace properly.

**Comment by FibrinLab** [comment]
Screenshot 2023-02-09 at 16 30 41

Screenshot 2023-02-09 at 16 10 04

@pavlovcik  Update:
1. Modified to "Build and Test" workflow to update number of lines covered
2. You would need to add your GITHUB auth token to the repository secrets as it is required by the Coverage CI (secrets.GIT_TOKEN
3. Added badges to show CI status in the development branch
4. Comments and reviews appreciated.

**Review by 0x4007 — CHANGES_REQUESTED** [review]
Don't commit `.env`

Updating forge-std seems wrong too.

I'll make sure that the RPC URL is using the selector script we already built.

**Comment by FibrinLab** [comment]
> Don't commit `.env`
> 
> Updating forge-std seems wrong too.
> 
> I'll make sure that the RPC URL is using the selector script we already built.

1. I removed the .env file. Seemed like the only solution to the "RPC_URL" error
2. The forge-std files was auto updated i think by a "forge" command. Any suggestions?
@pavlovcik Thanks

**Comment by 0x4007** [comment]
On my branch I just set the value to our ubq gateway i mentioned in the devpool chat. You can take a peak at my PR or you can standby for a little bit and pull when it's merged to see what I'm talking about. 

Revert the submodule changes probably

**Pull request closed without merging**
