### PR TITLE
Add support for more wallets

### LINKED ISSUE #19: Add WalletConnect Support
@Zequez this is a luxury and can be put on the backlog, but I could never figure out the interface the other wallets use (window.web3 ?) 

This is opera touch on iOS and it doesn't work. Would be awesome if we could add support :)

image

### PR DESCRIPTION
**Pull request by codeaddict99**
Added walletconnect wallet support
Closes: https://github.com/ubiquity/ubiquity-dollar/issues/19

### CODE REVIEW

**Comment by sergfeldman** [comment]
@Zequez Please, check this PR

**Comment by 0x4007** [comment]
Everything looks pretty good here. I just need to check with zapaz on why the CI/CD stopped working. Give us this week to circle back on this - don't worry it doesn't count against your timer!

**Comment by angrybird211** [comment]
Okay, Thank you for taking the time to review my PR.

**Comment by codeaddict99** [comment]
Issues are coming up in development branch on formatting.

image

**Comment by 0x4007** [comment]
Hey @kecrypto I can send the full compensation for this as long as you post your wallet address here. 

However, we will need to reimplement this from the latest code (you can collect another full bounty for doing it again, basically.)

We removed most classnames in the latest code, and I'll request that you reduce the warnings from the `yarn install` related to walletconnect. Also please don't use a switch case in this context, or type `any`.

I expect that formatting, CI and CD should all be good to go now!

**Comment by codeaddict99** [comment]
There is an issue on development branch which makes us disable to commit update


image

**Pull request closed without merging**
