### PR TITLE
chore: add testnet rpc tunnel workflow

### LINKED ISSUE #493: Testnet RPCs under ubq.fi domain
If we want to set up the temp Anvil deployments under a project domain then there is some setup required with the Cloudflare account that has that domain registered: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/

This action shows the secrets needed:
https://github.com/AnimMouse/setup-cloudflared

_Originally posted by @acaldas in https://github.com/ubiquity/ubiquity-dollar/issues/442#issuecomment-1372134563_

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves: #493

QA: https://github.com/gitcoindev/ubiquity-dollar/issues/1#issuecomment-1742622467 (and comments below).

### CODE REVIEW

**Comment by rndquu** [comment]
We already have pretty much the [same workflow](https://github.com/ubiquity/ubiquity-dollar/blob/dfe0e3f5da6200eb3058a22c3ef9d8d286ceb456/.github/workflows/setup-anvil.yml) for anvil so I don't think that we should merge the current PR.

Meanwhile we got a pretty much [detailed instructions](https://github.com/ubiquity/ubiquity-dollar/issues/493#issuecomment-1742664161) on how to setup custom domain for cloudflare tunnels so everything else is on us. I would:
1. Close the current PR **without merging**
2. Mark the issue as solved

**Comment by gitcoindev** [comment]
I am fine with @rndquu 's suggestion, the PR was to provide an example setup with QA.

**Comment by molecula451** [comment]
the [workflow](https://github.com/ubiquity/ubiquity-dollar/blob/dfe0e3f5da6200eb3058a22c3ef9d8d286ceb456/.github/workflows/setup-anvil.yml) probably will still need to be modified after set up everything at https://github.com/ubiquity/ubiquity-dollar/issues/493#issuecomment-1742664161 (which are clean instructions) so we either

1. Close and render new stuff after setup at https://github.com/ubiquity/ubiquity-dollar/issues/493#issuecomment-1742664161
2. Leave the PR open until everything setups and modify the stuff need it in this same PR

**Comment by rndquu** [comment]
> the [workflow](https://github.com/ubiquity/ubiquity-dollar/blob/dfe0e3f5da6200eb3058a22c3ef9d8d286ceb456/.github/workflows/setup-anvil.yml) probably will still need to be modified after set up everything at https://github.com/ubiquity/ubiquity-dollar/issues/493#issuecomment-1742664161

Yes, I will modify it

> Leave the PR open until everything setups and modify the stuff need it in this same PR

Bounty hunters don't need to wait for us until we do our stuff. They'd better start solving some other issue in the meantime. That is why I think that we can mark the [issue](https://github.com/ubiquity/ubiquity-dollar/issues/493) as solved.

**Comment by molecula451** [comment]
> > the [workflow](https://github.com/ubiquity/ubiquity-dollar/blob/dfe0e3f5da6200eb3058a22c3ef9d8d286ceb456/.github/workflows/setup-anvil.yml) probably will still need to be modified after set up everything at [#493 (comment)](https://github.com/ubiquity/ubiquity-dollar/issues/493#issuecomment-1742664161)
> 
> Yes, I will modify it
> 
> > Leave the PR open until everything setups and modify the stuff need it in this same PR
> 
> Bounty hunters don't need to wait for us until we do our stuff. They'd better start solving some other issue in the meantime. That is why I think that we can mark the [issue](https://github.com/ubiquity/ubiquity-dollar/issues/493) as solved.

+1

**Comment by gitcoindev** [comment]
Thank you for approving!

**Comment by molecula451** [comment]
keep us sending this quality sharing, code, info

**Pull request closed without merging**
