### PR TITLE
test: add more tests for ERC20Ubiquity contract

### PR DESCRIPTION
**Pull request by ryzhak**
This PR adds more tests for https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/ERC20Ubiquity.sol

Test coverage before:
```
|-------------------------------------------------+-----------------+-----------------+----------------+-----------------|
| src/dollar/ERC20Ubiquity.sol                    | 68.42% (13/19)  | 61.90% (13/21) |  0.00% (0/4)  | 91.67% (11/12) |
|-------------------------------------------------+-----------------+-----------------+----------------+-----------------|
```

Test coverage after:
```
|-------------------------------------------------+-----------------+-----------------+----------------+-----------------|
| src/dollar/ERC20Ubiquity.sol                    | 100.00% (19/19) | 100.00% (21/21) | 100.00% (4/4)  | 100.00% (12/12) |
|-------------------------------------------------+-----------------+-----------------+----------------+-----------------|
```

### CODE REVIEW

**Comment by 0x4007** [comment]
@ryzhak thanks for the surprise test coverage! Unfortunately we didn't set up a bounty for 100% test coverage on our token contracts and I'm unsure we really need it enough to pay for it! 

I'd like to request the input of @0xcodercrane and @sergfeldman on how to proceed here.

It looks like quite a bit of work was done here and we all appreciate the effort so I'm figuring out whats the best way to proceed!

**Comment by ryzhak** [comment]
sure, my point is that the best way to get to know the project is write tests for it )

**Comment by 0x4007** [comment]
> sure, my point is that the best way to get to know the project is write tests for it )

@0xcodercrane this seems like a great opportunity to delegate some needed test writing ASAP

**Comment by cuddle-dev** [comment]
Its also free for developers to contribute to our open-source project. Thanks for your contribution @ryzhak. we can merge your PR.

**Pull request merged**
