### PR TITLE
fix: warnings

### PR DESCRIPTION
**Pull request by 0x4007**
Got most of them but the following remain. If an easy fix feel free to take over this PR, otherwise I'll look into it later.

```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @codechecks/client@npm:0.1.12 doesn't provide typescript (pb3185), requested by ts-node
➤ YN0060: │ @ubiquity/dollar@workspace:packages/contracts/dollar provides @nomiclabs/hardhat-ethers (pe1017) with version 0.3.0-beta.13, which doesn't satisfy what @nomiclabs/hardhat-waffle requests
➤ YN0060: │ @ubiquity/ubiquistick@workspace:packages/contracts/ubiquistick provides @nomiclabs/hardhat-ethers (p86605) with version 0.3.0-beta.13, which doesn't satisfy what @nomiclabs/hardhat-waffle requests
➤ YN0002: │ typechain@npm:3.0.0 doesn't provide typescript (p4ba7f), requested by ts-essentials
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 421ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 400ms
➤ YN0000: Done with warnings in 1s 163ms
```

### CODE REVIEW

**Comment by cuddle-dev** [comment]
> Got most of them but the following remain. If an easy fix feel free to take over this PR, otherwise I'll look into it later.
> 
> ```
> ➤ YN0000: ┌ Resolution step
> ➤ YN0002: │ @codechecks/client@npm:0.1.12 doesn't provide typescript (pb3185), requested by ts-node
> ➤ YN0060: │ @ubiquity/dollar@workspace:packages/contracts/dollar provides @nomiclabs/hardhat-ethers (pe1017) with version 0.3.0-beta.13, which doesn't satisfy what @nomiclabs/hardhat-waffle requests
> ➤ YN0060: │ @ubiquity/ubiquistick@workspace:packages/contracts/ubiquistick provides @nomiclabs/hardhat-ethers (p86605) with version 0.3.0-beta.13, which doesn't satisfy what @nomiclabs/hardhat-waffle requests
> ➤ YN0002: │ typechain@npm:3.0.0 doesn't provide typescript (p4ba7f), requested by ts-essentials
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed in 0s 421ms
> ➤ YN0000: ┌ Link step
> ➤ YN0000: └ Completed in 0s 400ms
> ➤ YN0000: Done with warnings in 1s 163ms
> ```

it looks this happens because codechecks/client is not typescript package.  what I am thinking of a way to fix warnings is to find another dependency which is written in ts. but warning will not break the product running.

**Comment by 0x4007** [comment]
> but warning will not break the product running.

Consider this as part of my ongoing effort to reduce technical debts everywhere possible. 

I ebb and flow between being able to directly work on the code and everything else in the organization. Unfortunately it usually comes down to me personally to reduce technical debt. This would be probably my fifth go at it since starting the project lol

**Comment by 0x4007** [comment]
Releasing this work into the devpool. Somebody else can take this over and merge!

**Comment by cuddle-dev** [comment]
we'll continue in coming year

**Pull request closed without merging**
