### PR TITLE
refactor: remove CreditNft mock

### PR DESCRIPTION
**Pull request by rndquu**
This PR:
1. Removes the `CreditNft` mock contract
2. Refactors tests to use the real `CreditNft` contract

### CODE REVIEW

**Review by molecula451 — APPROVED** [review]

**Comment by molecula451** [comment]
are we purging many of the mocks contracts if not all? @rndquu

**Comment by rndquu** [comment]
> are we purging many of the mocks contracts if not all? @rndquu

All of [them](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks)

**Comment by 0x4007** [comment]
> > are we purging many of the mocks contracts if not all? @rndquu
> 
> All of [them](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks)

I thought the purpose of mock contracts was to make writing unit tests easier? Why should we remove them? Is it insufficient to continue using mocks for unit tests?

**Comment by rndquu** [comment]
> > > are we purging many of the mocks contracts if not all? @rndquu
> > 
> > 
> > All of [them](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks)
> 
> I thought the purpose of mock contracts was to make writing unit tests easier? Why should we remove them? Is it insufficient to continue using mocks for unit tests?

You're right, mocks make unit tests easier. On the frontend, for example, you can mock API calls. On the backend, for example, you can mock DB queries. But in the contracts it is not a big deal to deploy everything you need locally.

Check the [mocks](https://github.com/ubiquity/ubiquity-dollar/tree/6428a33696230ca019efaa5d227ec889c21a07c0/packages/contracts/src/dollar/mocks) folder. It arises a question:
- Why do we need to mock `CreditNft`, `CreditToken`, `DollarToken`, `UbiquiStick` when we can simply use the real contracts?

I understand why Curve's contracts were mocked (because they should be compiled with vyper and it is tricky to set it up in foundry) but other contract should not have been mocked. Your mock implementation can differ from a real contract hence there might be errors in unit tests while using the real contracts make sure that everything will work fine in production.

**Comment by molecula451** [comment]
I agree in testing real contracts on forked chain than having mocks and mocks for each update

**Review by 0x4007 — APPROVED** [review]

**Pull request merged**
