### PR TITLE
test: verify getCreditReturnedForDollars and getCreditNftReturnedForDollars

### LINKED ISSUE #838: Increase facet contracts forge / unit tests coverage
The goal is to facilitate AI and see if we can increase unit test coverage to 100% for all facets.

### PR DESCRIPTION
**Pull request by gitcoindev**
Increases CreditNftManagerFacet test coverage, part of #838 .

Resolves: #838

### CODE REVIEW

**Comment by gitcoindev** [comment]
Development branch coverage: 69.7
PR branch coverage: 70.1

**Comment by molecula451** [comment]
time for a github action bots to post coverall increase comment? on PR it would be nice @gitcoindev

**Comment by gitcoindev** [comment]
> time for a github action bots to post coverall increase comment? on PR it would be nice @gitcoindev

I also thought about it. Currently the coverage difference it is available in the GitHub action logs, and does not pollute comments. I am not sure to be honest if we really need it to add in each pull request comment thread. For pull requests that try to increase coverage it is a good indicator, but for bug fixes and new features it may be enough if the GitHub action does not fail with decreased coverage. Perhaps @pavlovcik could you please also share your thoughts?

**Review by rndquu — APPROVED** [review]

**Review by molecula451 — APPROVED** [review]

**Comment by 0x4007** [comment]
I don't see the benefit of that if we can easily see the results on CI

**Pull request merged**
