### PR TITLE
fix: build error on fresh yarn.lock file

### LINKED ISSUE #377: Build fails on a fresh yarn.lock
On a fresh install there is a build error `Module not found: Can't resolve 'jotai-immer'`

How to reproduce:
1. Delete `yarn.lock`
2. Run `yarn install`
3. Run `yarn build:all`

Gives the following:
```
➤ YN0000: No files changed, compilation skipped
➤ YN0000: info  - Linting and checking validity of types...
➤ YN0000: warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
➤ YN0000: 
➤ YN0000: ./pages/404.tsx
➤ YN0000: 12:82  Warning: Replace `Docs` with `⏎··············Docs⏎············`  prettier/prettier
➤ YN0000: 15:56  Warning: Replace `FAQ` with `⏎··············FAQ⏎············`  prettier/prettier
➤ YN0000: 18:77  Warning: Replace `Github` with `⏎··············Github⏎············`  prettier/prettier
➤ YN0000: 21:63  Warning: Replace `Discord` with `⏎··············Discord⏎············`  prettier/prettier
➤ YN0000: 24:58  Warning: Replace `Telegram` with `⏎··············Telegram⏎············`  prettier/prettier
➤ YN0000: 27:65  Warning: Replace `Twitter` with `⏎··············Twitter⏎············`  prettier/prettier
➤ YN0000: 
➤ YN0000: ./pages/index.tsx
➤ YN0000: 13:10  Warning: 'twapPrice' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/bonds/App.tsx
➤ YN0000: 36:10  Warning: 'showAdminComponents' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/lib/hooks/useDeployedAddress.tsx
➤ YN0000: 6:41  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
➤ YN0000: 
➤ YN0000: ./components/lib/hooks/useWeb3.tsx
➤ YN0000: 9:7  Warning: 'LOCAL_NODE_ADDRESS' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/redeem/UcrRedeem.tsx
➤ YN0000: 15:10  Warning: 'USDC_ADDRESS' is defined but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/staking/BondingSharesExplorer.tsx
➤ YN0000: 244:38  Warning: 'sharesBalance' is defined but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: 
➤ YN0000: ./components/utils/deployments.ts
➤ YN0000: 3:49  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
➤ YN0000: 7:96  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
➤ YN0000: 
➤ YN0000: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
➤ YN0000: info  - Creating an optimized production build...
➤ YN0000: Failed to compile.
➤ YN0000: 
➤ YN0000: ../../node_modules/jotai/esm/immer.mjs
➤ YN0000: Module not found: Can't resolve 'jotai-immer' in '/Users/rndquu/Public/projects/blockchain/ubiquity-dollar-rndquu/node_modules/jotai/esm'
➤ YN0000: 
➤ YN0000: Import trace for requested module:
➤ YN0000: ../../node_modules/jotai/esm/immer.mjs
➤ YN0000: ../../node_modules/@uniswap/widgets/dist/index.js
➤ YN0000: ./components/redeem/UcrRedeem.tsx
➤ YN0000: 
➤ YN0000: 
➤ YN0000: > Build failed because of webpack errors
➤ YN0000: Done in 1m 5s
```

### PR DESCRIPTION
**Pull request by Steveantor**
fix: this PR resolves the build error on fresh _yarn.lock_ file. 

some sub/deps might not be strictly following **semver**)
We may also .gitignore yarn.lock (optional)

Resolves #377

### CODE REVIEW

**Comment by 0x4007** [comment]
Sorry but we recently upgraded to the conventional commits standard. Please recommit the message according to the standard.

**Comment by Steveantor** [comment]
> Sorry but we recently upgraded to the conventional commits standard. Please recommit the message according to the standard.

updated @pavlovcik

**Comment by 0x4007** [comment]
> > Sorry but we recently upgraded to the conventional commits standard. Please recommit the message according to the standard.
> 
> updated @pavlovcik

The CI checks the commit messages not the PR name lol

**Comment by Steveantor** [comment]
> > > Sorry but we recently upgraded to the conventional commits standard. Please recommit the message according to the standard.
> > 
> > 
> > updated @pavlovcik
> 
> The CI checks the commit messages not the PR name lol

Also updated the description as per the `commit editor`
I'm relatively new to conventional tooling :)

**Comment by 0x4007** [comment]
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by Steveantor** [comment]
replacing this PR with another one.

**Comment by Steveantor** [comment]
delete this PR to avoid cluttering (#405 takes precedence)
@pavlovcik

**Comment by 0x4007** [comment]
> delete this PR to avoid cluttering (#405 takes precedence) @pavlovcik

I'm not sure how to delete

**Pull request closed without merging**
