### PR TITLE
refactor: remove unused contracts

### PR DESCRIPTION
**Pull request by rndquu**
This PR removes unused contracts and interfaces

### CODE REVIEW

**Review by 0x4007 — COMMENTED** [review]
I thought we are using one of the master chefs at least. This needs @zgorizzo69 input

**Comment by rndquu** [comment]
> I thought we are using one of the master chefs at least. This needs @zgorizzo69 input

We use [ChefFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ChefFacet.sol) + [interface for it](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/interfaces/IUbiquityChef.sol), all other chef interfaces seems to be redundant

**Review by 0x4007 — APPROVED** [review]

**Comment by 0x4007** [comment]
> > I thought we are using one of the master chefs at least. This needs @zgorizzo69 input
> 
> 
> 
> We use [ChefFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ChefFacet.sol) + [interface for it](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/interfaces/IUbiquityChef.sol), all other chef interfaces seems to be redundant

That checks out because I recall having unused backups as reference in the early days of this repository.

**Comment by rndquu** [comment]
@zgorizzo69 pls check this PR

**Review by zgorizzo69 — APPROVED** [review]

**Pull request merged**
