### PR TITLE
Changed "Bonding Contract" Contract name to "Staking"

### LINKED ISSUE #164: Change "Bonding Contract" Contract name to "Staking"
2022-05-12 21_20_13-Telegram (480019)

### PR DESCRIPTION
**Pull request by codeaddict99**
Changed "Bonding Contract" Contract name to "Staking"
Closes: https://github.com/ubiquity/ubiquity-dollar/issues/164

### CODE REVIEW

**Comment by sergfeldman** [comment]
@Zequez Please, check this PR

**Comment by 0x4007** [comment]
Hey @kecrypto sorry for the delay. I'll send the full USDC and UBQ amount, please post your USDC Ethereum mainnet wallet address here!

**Comment by codeaddict99** [comment]
Cool !  My wallet address is    0x458d548a0b069484226c66fCba7Ae192C232dBBa

**Comment by cuddle-dev** [comment]
I think this branch has conflicts. so we think both stuff are still remaining
- [ ] Resolve conflicts 
- [ ] Github ci/cd pass!

@kecrypto we'll appreciate it a lot if you get above things resolved in order to merge this pull request

**Comment by codeaddict99** [comment]
Okay, I'll merge and  commit the udpate soon

**Comment by 0x4007** [comment]
> I think this branch has conflicts. so we think both stuff are still remaining
> 
> * [ ]  Resolve conflicts
> * [ ]  Github ci/cd pass!
> 
> @kecrypto we'll appreciate it a lot if you get above things resolved in order to merge this pull request

Hey @0xcodercrane thanks for jumping in here but because it was my fault for 1. taking a month to circle back and 2. introducing all the merge conflicts in that month: I'll take responsibility for those two points.

To be honest, I already handled changing it into staking in my commits, but I still think that @kecrypto should be paid for his work.

USDC Payment https://etherscan.io/tx/0xecad85562a753dd93affb0b7e90f9fd42b4fc100797acb02130b6842da9c8bb5
UBQ Payment https://etherscan.io/tx/0xd687ae14ef4cf87d092f7662f510b1199afc38df337f30cdf62a6320526d7c09

Thanks @kecrypto! Sorry again for the delays. The bounty program is still nascent and we're working on fixing things up to run more efficiently. I expect that we shouldn't run into this sort of issue again since we have 3x CI/CD operational now!

**Pull request closed without merging**
