### PR TITLE
test: rename testFail tests

### LINKED ISSUE #414: Don't want to have unit tests named `testFail`
## Problem

There are a few unit tests names `testFail*` which means it passes even though it fails. we need to remove `Fail` from those functions

### PR DESCRIPTION
**Pull request by rndquu**
Resolves #414 

The only left `testFail` is this one: https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/core/DollarMintExcess.t.sol#L94

This test reverts but should not (as noted in the comments https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/core/DollarMintExcess.t.sol#L98), that is why its name is not updated

### CODE REVIEW

**Comment by cuddle-dev** [comment]
sorry for jumping late on this issue. @rndquu you need to rebase from feat/406-protocol-deploy-script because it has more testFail functions.

**Comment by rndquu** [comment]
> sorry for jumping late on this issue. @rndquu you need to rebase from feat/406-protocol-deploy-script because it has more testFail functions.

I've checked this branch https://github.com/ubiquity/ubiquity-dollar/tree/feat/406-protocol-deploy-script

There are 5 places where `testFail` is used:
1. https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/ERC4626.t.sol (fixed in this PR)
2. https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/core/DollarMintExcess.t.sol (expected to fail, wating for fix)
3. https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/DirectGovernanceFarmer.t.sol
4. https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/core/CreditNFT.t.sol
5. https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/manager/facets/ManagerFacet.t.sol

`testFail` tests for `DirectGovernanceFarmer`, `CreditNFT` and `ManagerFacet` are introduced only on the `feat/406-protocol-deploy-script` branch

Check the following tests:
- https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/manager/facets/ManagerFacet.t.sol#L125
- https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/core/CreditNFT.t.sol#L32
- https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/DirectGovernanceFarmer.t.sol#L226
- https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/DirectGovernanceFarmer.t.sol#L340

As far as I understand they are expected to pass but there was kind of a hot fix https://github.com/ubiquity/ubiquity-dollar/commit/030a7a393ec04225141fc4a4c0f7145a6367cd61 which marked them as "expected to fail"

I think the author of the target branch `feat/406-protocol-deploy-script` should fix failing tests because he has more context on what has been updated and why

**Comment by 0x4007** [comment]
It looks like @0xcodercrane forgot about this pull request. This is outside of my scope of expertise but I think it looks good to merge. @rndquu if you think so then please merge this and you can collect the bounty by commenting your wallet address on #414

**Comment by rndquu** [comment]
> It looks like @0xcodercrane forgot about this pull request. This is outside of my scope of expertise but I think it looks good to merge. @rndquu if you think so then please merge this and you can collect the bounty by commenting your wallet address on #414

I would rather wait for @0xcodercrane response

The only place left with `testFail` in the `feat/406-protocol-deploy-script` branch is https://github.com/ubiquity/ubiquity-dollar/blob/feat/406-protocol-deploy-script/packages/contracts/test/dollar/core/CreditNFT.t.sol#L31 

As far as I understand that test is expected to pass

**Comment by 0x4007** [comment]
> I would rather wait for @0xcodercrane response 

I asked on Telegram

**Review by cuddle-dev — CHANGES_REQUESTED** [review]
https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/core/DollarMintExcess.t.sol#L94

Can I know the reason why you couldn't get this resolved?  
What I wanted to originally resolve on this issue was such kind of fixes. Would you please spend more time on it? @rndquu

**Comment by rndquu** [comment]
> https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/core/DollarMintExcess.t.sol#L94
> 
> Can I know the reason why you couldn't get this resolved? What I wanted to originally resolve on this issue was such kind of fixes. Would you please spend more time on it? @rndquu

I've updated tests for the `DollarMintExcess` contracts. Tests are now passing without `testFail`

PR is ready for review

**Review by cuddle-dev — APPROVED** [review]

**Review by 0x4007 — COMMENTED** [review]
Hard for me to tell what's good so if @0xcodercrane approves its fine by me.

**Pull request merged**
