### PR TITLE
fix: remove unreachable return

### PR DESCRIPTION
**Pull request by rndquu**
This PR removes an unreachable return mentioned [here](https://github.com/ubiquity/ubiquity-dollar/issues/684#issuecomment-1597166172)

### CODE REVIEW

**Review by 0x4007 — APPROVED** [review]
Makes sense to me

**Comment by pavlovcik** [comment]
Shouldn't we run `LibTWAPOracle.update();` before the `return` ?

**Review by 0x4007 — COMMENTED** [review]
Shouldn't we run `LibTWAPOracle.update();` before the `return` ? Updating the oracle seems like a good idea.

**Comment by rndquu** [comment]
> Shouldn't we run `LibTWAPOracle.update();` before the `return` ? Updating the oracle seems like a good idea.

It is already updated in all of the functions where `_getPercentDeviationFromUnderPeg()` is used ([one](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibCurveDollarIncentive.sol#L112) and [two](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibCurveDollarIncentive.sol#L135))

**Review by 0x4007 — APPROVED** [review]

**Pull request merged**
