### PR TITLE
Added badges and coverage workflow

### LINKED ISSUE #482: Add build badges and update test coverage config
What should be done:
1. Add CI build badge at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md with the current CI build status (success or fail)
2. Add test coverage badge with % of lines covered by tests at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md
3. Remove the following files from the test coverage report:

- `src/dollar/libs/*`
- `src/dollar/mocks/*`
- `src/dollar/utils/*`
- `src/manager/libraries/*`
- `src/ubiquistick/MockUBQmanager.sol`
- `test/*`

Build badge docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

### PR DESCRIPTION
**Pull request by FibrinLab**
Resolves #482

### CODE REVIEW

**Comment by FibrinLab** [comment]
@pavlovcik I cleaned up the commit messages. I also added a github workflow file to handle badges and commit. I also modified the rpc url to point to https://eth.ubq.fi/v1/mainnet

**Comment by 0x4007** [comment]
Make sure the CI passes before requesting a review (minus the Slither stuff.) It looks like its complaining about the RPC_ENDPOINT

**Comment by FibrinLab** [comment]
> Make sure the CI passes before requesting a review (minus the Slither stuff.) It looks like its complaining about the RPC_ENDPOINT

@pavlovcik Apologies about that. I don't think the failing "install and build workflow" CI is unique to my branch. I noticed a fix was pushed to development but after merging, the CI still fails. Any recommendations?

**Comment by 0x4007** [comment]
> > Make sure the CI passes before requesting a review (minus the Slither stuff.) It looks like its complaining about the RPC_ENDPOINT
> 
> @pavlovcik Apologies about that. I don't think the failing "install and build workflow" CI is unique to my branch. I noticed a fix was pushed to development but after merging, the CI still fails. Any recommendations?

@rndquu

**Comment by rndquu** [comment]
> > Make sure the CI passes before requesting a review (minus the Slither stuff.) It looks like its complaining about the RPC_ENDPOINT
> 
> @pavlovcik Apologies about that. I don't think the failing "install and build workflow" CI is unique to my branch. I noticed a fix was pushed to development but after merging, the CI still fails. Any recommendations?

"build and test" ci action fails with:
```
[FAIL. Reason: Failed to resolve env var `RPC_URL` in `${RPC_URL}`: environment variable not found] setUp() (gas: 0)
```

here https://github.com/ubiquity/ubiquity-dollar/pull/534/files#diff-c60e9fff67fed3b9d207c5d83584970bcdae60dbefc05e793fd79f5153ce0498R40 `RPC_URL` env variable is added. I guess it is not set in the repo so the CI action fails. Why do we need this `RPC_URL` in the workflow config?

**Pull request closed without merging**
