### PR TITLE
Feat/ape in

### LINKED ISSUE #5: Update UBQ Farming UI
We changed the flow from manual steps (add liquidity in curve, then lockup LP token in our staking contract) to now “ape in” which handles both in a single transaction. Check `packages/contracts/src/dollar/DirectGovernanceFarmer.sol`

The new UI should be built on top of the related smart contact code changes. The context is available in https://github.com/ubiquity/ubiquity-dollar/issues/243

image

You can upgrade the "Stake Liquidity to Receive UBQ" panel with one that allows users to: 
1. Deposit their uAD+3pool stables (uAD/USDC/USDT/DAI) allow them to select the amount of each of course.
2. Specify the amount of weeks for lockup.
3. Be sure to leave the MAX button functionality in here as well.

Using the `apeIn` method!

### LINKED ISSUE #341: Update UBQ Farming UI
We changed the flow from manual steps (add liquidity in curve, then lockup LP token in our staking contract) to now “ape in” which handles both in a single transaction. 

The new UI should be built on top of the related smart contact code changes. The context is available in the below issue. 

https://github.com/ubiquity/ubiquity-dollar/issues/243

### PR DESCRIPTION
**Pull request by zgorizzo69**
Resolves ubiquity/uusd.ubq.fi#5

### CODE REVIEW

**Comment by zgorizzo69** [comment]
## done
- refactor `DepositShare` to extract `APR` component
- added a dropdown component following ubiquity theme with token icons in menu Items (not used yet)
- added a `TokenAmountInput` component inspired by crv.to that takes in the token icon/ decimal/ balance
image
- added a  `DepositStables` parent component to display the different `TokenAmountInput` needed to ape In 🐵 + `Max` button to ape like a chad 
---
## todo
- plug ApeIn to trigger `/packages/contracts/src/dollar/DirectGovernanceFarmer.sol` deposit I guess

**Comment by 0x4007** [comment]
I guess the plan is to wait until we fix the UI ubiquity/ubiquity-dollar#354 to verify that this PR works?

**Comment by 0x4007** [comment]
Instead of adding a WIP label @zgorizzo69 I suggest you leave this as a draft pull request until it is no longer a "work in progress"

**Comment by 0x4007** [comment]
>   image

I wish I could see this rendered in my browser and push a few small CSS fixes. 

Perhaps you have some advice on how to set it up on my local so I can contribute while we wait for https://github.com/ubiquity/ubiquity-dollar/issues/354 fix?

I just tried deploying locally and realize that we don't have clear instructions in the readme on how to set up Anvil, and how to deploy everything.

**Comment by zgorizzo69** [comment]
> > image
> 
> I wish I could see this rendered in my browser and push a few small CSS fixes.
> 
> Perhaps you have some advice on how to set it up on my local so I can contribute while we wait for ubiquity/ubiquity-dollar#354 fix?
>I just tried deploying locally and realize that we don't have clear instructions in the readme on how to set up Anvil, and how to deploy everything.

I will add that script as part of the issue https://github.com/ubiquity/ubiquity-dollar/issues/371 which I am currently working on
To test right now We have to run a fork with `anvil` and get some tokens with `cast`

**Comment by sergfeldman** [comment]
@zgorizzo69 https://etherscan.io/tx/0x566884b38af8be1818497824a2dbb84a57bc0074dcf7a9069a242661387f32a8

**Comment by 0x4007** [comment]
> @zgorizzo69 https://etherscan.io/tx/0x566884b38af8be1818497824a2dbb84a57bc0074dcf7a9069a242661387f32a8

Same as our other discussion. The linked PR is not merged so this bounty is not complete.

**Comment by 0x4007** [comment]
Hey I tried fixing the merge conflicts but I changed a couple things I want to make sure they are good by you:

1. I changed your `require` to `imports` which also means those functions must be async. 
2. I changed the function names `Deposit` -> `DepositSingle` and `DepositMulti` -> `DepositMultiple` in `packages/contracts/src/dollar/DirectGovernanceFarmer.sol` to make the naming clearer.
    - looks like there are no tests for depositMultiple?

Would you mind looking into this regex issue? https://github.com/ubiquity/ubiquity-dollar/pull/367/checks?check_run_id=10682296782

**Comment by zgorizzo69** [comment]
> Hey I tried fixing the merge conflicts but I changed a couple things I want to make sure they are good by you:
> 
>     1. I changed your `require` to `imports` which also means those functions must be async.
fine by me !

> 
>     2. I changed the function names `Deposit` -> `DepositSingle` and `DepositMulti` -> `DepositMultiple` in `packages/contracts/src/dollar/DirectGovernanceFarmer.sol` to make the naming clearer.
>        
>        * looks like there are no tests for depositMultiple?
check test named `testDeposit_Multiple_Tokens***`
> 
> 
> Would you mind looking into this regex issue? https://github.com/ubiquity/ubiquity-dollar/pull/367/checks?check_run_id=10682296782

yep

**Comment by 0x4007** [comment]
> check test named `testDeposit_Multiple_Tokens***`

I officially screwed up this PR then because I deleted these in 37285f8c1c3cd6095604f96b75a1b66fad69c0b2. Should I just revert? Lol

Screenshot 2023-01-17 at 20 19 36

**Pull request closed without merging**
