### PR TITLE
feat: add an addresses table to README

### PR DESCRIPTION
**Pull request by zugdev**
At [this task in a neighbor repo](https://github.com/ubiquity/ubq.fi/issues/40#issuecomment-2458215077) we agreed it was a good idea to have an addresses table to aggregate deployment information. Perhaps this could be handy here too. Take it as a suggestion and feel free to close, merge or change it.

### CODE REVIEW

**Comment by rndquu** [comment]
@zugdev 

Most of the contracts mentioned in this PR are deprecated and will never be used again. There's [this](https://github.com/ubiquity/ubiquity-dollar/wiki/24.-Smart-Contracts) list of our current relevant contract deployments.

You could either refactor current PR to mention contracts from https://github.com/ubiquity/ubiquity-dollar/wiki/24.-Smart-Contracts either create a new wiki page with the deprecated contracts (because it'd be useful for staking v2).

**Comment by zugdev** [comment]
Would you rather:

1. Have both useful and deprecated deployments tables in wiki

2. Have useful deployments table in readme and deprecated in wiki

3. Have useful table in readme and both in wiki too

**Comment by rndquu** [comment]
> Would you rather:
> 
> 1. Have both useful and deprecated deployments tables in wiki
> 2. Have useful deployments table in readme and deprecated in wiki
> 3. Have useful table in readme and both in wiki too

Useful deployments could be placed in the readme file, deprecated deployments could be placed in wiki for future references

**Comment by zugdev** [comment]
If you check the [wiki's sidebar](https://github.com/ubiquity/ubiquity-dollar/wiki/_Sidebar/_edit), there is a reference to "Smart Contracts (legacy)".

image

That page is empty, and I think the order is wrong. I will change the sidebar and add a new page below the 24th for the deprecated contracts.

--- 

The new page is [Deprecated Deployments](https://github.com/ubiquity/ubiquity-dollar/wiki/25.-Deprecated-Deployments). I've also updated the sidebar accordingly.

**Review by rndquu — APPROVED** [review]

**Pull request merged**
