### PR TITLE
Feature/format contracts prettier plugin solidity

### LINKED ISSUE #839: Enforce same line bracket opens in Solidity
A custom `lint-staged` script would need to run to enforce this bracket style on commits. I was unable to find a tool out-of-the-box for this but it is possible that they exist. 

> > @rndquu we are having styling issues, we should decide whether to allow
> > ```solidity
> > function setRndnuu() private {
> >     // code
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```solidity
> > function setRndnuu() private
> > {
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this can be seen here as well as many other parts of the code
> 
> I guess the linter [decides](https://github.com/ubiquity/ubiquity-dollar/blob/10739ec9952bac4f588bde7bc4ca191d941f1dc7/package.json#L55) how to format code

I looked into this and we would have to make a custom tool to enforce this with lint-staged I believe.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/832#issuecomment-1818047062_

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves #839 

* enforce prettier-plugin-solidity for packages/contracts solidity files
* improve `format:all`
* upgrade prettier-plugin-solidity to 1.2.0

Plus fix prettier output for IUbiquityGovernance.sol

### CODE REVIEW

**Comment by molecula451** [comment]
Please, provide QA, which pattern is following?

**Comment by gitcoindev** [comment]
> Please, provide QA, which pattern is following?

@molecula451 sure, please check the QA demo below: I am changing one contract, one test file, two places each and prettier is fixing the layout during pre-commit stage.

https://github.com/ubiquity/ubiquity-dollar/assets/88761781/26869f36-93a0-44c5-9361-0663c1437ea6

**Comment by rndquu** [comment]
images

**Review by rndquu — APPROVED** [review]

**Comment by 0x4007** [comment]
> @molecula451 sure, please check the QA demo below: I am changing one contract, one test file, two places each and prettier is fixing the layout during pre-commit stage.
> 
>  prettier_qa_demo.mp4

That's crazy to me that you're using vim without syntax highlighting. 

For future reference, you do not need to request a review from me in this repository as most of the work involves Solidity and I am not a Solidity expert.

**Review by 0x4007 — APPROVED** [review]
To be honest I couldn't make much sense of what exactly was happening in your video, but the code seems fine.

**Comment by gitcoindev** [comment]
> > @molecula451 sure, please check the QA demo below: I am changing one contract, one test file, two places each and prettier is fixing the layout during pre-commit stage.
> > prettier_qa_demo.mp4
> 
> That's crazy to me that you're using vim without syntax highlighting.

:rofl: 

> 
> For future reference, you do not need to request a review from me in this repository as most of the work involves Solidity and I am not a Solidity expert.

All right, will remember that. You were set as a default when I opened the pull request.

**Comment by gitcoindev** [comment]
Merging with 2 approvals.

**Comment by molecula451** [comment]
@gitcoindev please, wait for my full review as I am working on other sections of the repo

**Comment by gitcoindev** [comment]
All right, though this one was already closed. Fortunately you should be able to easily rebase your branch on top of development as it does not affect existing code much and should not change anything in your pull request.

**Comment by molecula451** [comment]
no worries, but the best ideal is to have everyones feedback before it gets merged, unless! and unless! the implementation is absolutely clear

**Comment by molecula451** [comment]
no worries, but the best ideal is to have everyones feedback before it gets merged, unless! and unless! the implementation is absolutely clear to everyones eyes

**Pull request merged**
