### PR TITLE
refactor: refactor tests to maintain a single naming convention

### LINKED ISSUE #480: Refactor tests to maintain a single naming convention
Refactor tests using the following convention test[MethodName]_[ExpectedResult]_[Condition]

Examples:

- https://github.com/cryptexfinance/contracts/blob/master/test/HardETHVaultHandler.t.sol#L74
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/ERC20Ubiquity.t.sol#L81

### PR DESCRIPTION
**Pull request by pwilson77**
Resolves #480

### CODE REVIEW

**Comment by rndquu** [comment]
@pwilson77 

thank you for the PR

1. This is totally my fault but I meant to refactor test names with low dashes like `testConstructor_ShouldRevert_WhenBurnFeeIsHigh`. Could you please refactor code with low dashes?
2. Pls merge the `development` branch (there is a fix for CI build there)
3. Pls fix the conflicts

**Comment by pwilson77** [comment]
oh alright will make those fixes

**Comment by pwilson77** [comment]
Hi @rndquu  could u review I made the changes but the same CI checks keeps failing

**Comment by rndquu** [comment]
> Hi @rndquu could u review I made the changes but the same CI checks keeps failing

Hi, thank you for the update, I will check it today

**Comment by 0x4007** [comment]
@rndquu I just told CI to re-run please recheck soon!

**Comment by rndquu** [comment]
@pwilson77 

1. Pls merge the latest updated from the `development` branch
2. Some of the tests are failing because of a string mismatch, ex: https://github.com/ubiquity/ubiquity-dollar/pull/532/files#diff-827ff987b6797b6cac2dfa68cd5920a68c648799d2cb37e5582ceb4a0379d156L31 => `Credit NFT manager ` vs `CreditNFT manager`
3. When test starts with `testFail` then it is expected to revert (this is a special forge syntax  https://book.getfoundry.sh/forge/writing-tests). When you rename, for example `testFailWithdraw` to `testWithdraw`, then `testWithdraw` is gonna fail because it is not expected to revert but reverts nevetheless. Simply put you may omit renaming tests that start with `testFail`, we're in the process of getting rid of all of them.

**Comment by pwilson77** [comment]
Oh ok , making those changes

**Comment by pwilson77** [comment]
Hi @rndquu, the CI checks have passed now, could u check the PR

**Comment by 0x4007** [comment]
We just renamed `NFT` to `Nft` in our codebase (camelCase for variables, functions, and file names) once you do that this can auto-merge.

**Comment by rndquu** [comment]
> We just renamed `NFT` to `Nft` in our codebase (camelCase for variables, functions, and file names) once you do that this can auto-merge.

This is not described in the original issue so I guess we can skip this requirement for now. I can do it later.

Overall the PR looks good so @pwilson77 pls fix the conflicts so that this PR could be merged.

**Review by rndquu — APPROVED** [review]

**Comment by pwilson77** [comment]
Ok fixing the conflicts then

**Comment by pwilson77** [comment]
Hi @rndquu, fixed the conflicts and I had to do the renaming of `NFT` to `Nft` because I had CI errors, could u merge I am not sure why the auto-merge didn't work

**Comment by rndquu** [comment]
@pavlovcik seems fine to me, ready to be merged

**Comment by pwilson77** [comment]
Hi @pavlovcik, could you check the PR

**Pull request merged**
