### PR TITLE
chore: upload audit report

### PR DESCRIPTION
**Pull request by molecula451**
Making use of & taking the best from the audit contest

### CODE REVIEW

**Comment by 0x4007** [comment]
I think its fine when it passes CI!

**Review by rndquu — APPROVED** [review]

**Comment by molecula451** [comment]
leave us your comments or send us PR to enhance the audit outlook gitcoindev!

**Comment by gitcoindev** [comment]
@molecula451 I read it after the merge, we are part of history now. Yes, I will keep fixing the minor findings as well!

**Review by gitcoindev — COMMENTED** [review]
Looks good

**Pull request merged**
