### PR TITLE
Convert Project From Hardhat to Foundry #206

### PR DESCRIPTION
**Pull request by george-shammar**
This PR seeks to merge the following changes. #206 

- [ ] Complete replacement of Hardhat configurations and project setup to Foundry. - CONFIG

- [ ] Incorporation of already implemented priceReset task into the updated  #project. #210 

- [ ] Update deployment scripts so that contracts will deploy on the local Foundry (Anvil) blockchain.

- [ ]  Port all tests.

### CODE REVIEW

**Comment by pavlovcik** [comment]
@george-shammar I suggest that you make this a draft PR until its ready. Once its ready you can assign me as a reviewer!

**Comment by george-shammar** [comment]
> @george-shammar I suggest that you make this a draft PR until its ready. Once its ready you can assign me as a reviewer!

Okay. Thanks.

**Comment by pavlovcik** [comment]
Why not rename test files with `test` in the name vs `t`?

**Comment by george-shammar** [comment]
> Why not rename test files with `test` in the name vs `t`?

Using for example "Contract.t.sol" as against "Contract.test.sol" is a foundry convention. However, tests are still passing after adopting "Contract.test.sol" format. Going forward, I'll use the format.

**Comment by 0xcodercrane** [comment]
> Why not rename test files with `test` in the name vs `t`?

.t.sol and .s.sol are the formats foundry recommends. so I am ok to go with *.t.sol

**Comment by pavlovcik** [comment]
> > Why not rename test files with `test` in the name vs `t`?
> 
> Using for example "Contract.t.sol" as against "Contract.test.sol" is a foundry convention. Same with deployment scripts e.g "Contract.s.sol". However, tests are still passing after adopting "Contract.test.sol" format. Going forward, I'll use the "Contract.test.sol" format.

Thank you for the response. Let's just stick with Foundry conventions then!

**Pull request closed without merging**
